NOTICE, README.md, docs/documentation/01-getting-started.md, docs/documentation/02-architecture.md, docs/documentation/03-commands.md, docs/documentation/04-events.md, docs/documentation/05-entities.md, docs/documentation/06-read-models.md, docs/documentation/07-auth.md, docs/documentation/08-deployment.md, docs/documentation/09-rest-api.md, docs/documentation/README.md, docs/examples/README.md, docs/examples/cart-service/README.md
- Improved structure, adding dedicated examples and documentation folders.
- Added a page for Read Models
- Added a specific page to document the REST API
=> Documentation organization improvements

docs/examples/cart-service/README.md
**Changes:**
- This PR fixes a small formatting issue
- Adds some information about how to create a read model
- Adds some information about how to use read models
=> Updates readme to include information about read models

packages/framework-core/src/decorators/projection.ts, packages/framework-core/test/annotations/read-model.test.ts, packages/framework-example/src/read-models/cart-read-model.ts
The reason is to be consistent with other decorators
=> Change "@Projection" by "@Projects"

packages/framework-core/package.json, packages/framework-core/src/idGenerator.ts, packages/framework-core/src/index.ts, packages/framework-core/test/annotations/entity.test.ts, packages/framework-example/src/commands/create-product.ts, packages/framework-example/src/events/changed-cart-item.ts, packages/framework-example/src/events/product-deleted.ts, packages/framework-example/src/events/updated-shipping-address.ts, packages/framework-provider-aws/src/library/events-adapter.ts, packages/framework-provider-aws/src/library/partition-keys.ts, packages/framework-types/package.json, packages/framework-types/src/concepts/uuid.ts, packages/framework-types/src/envelope.ts, packages/framework-types/src/provider.ts
This way, the type and the way to generate values of that type are as close as possible.
=> Add method 'generate()' to UUID type

docs/examples/cart-service/README.md
- Improve some wording that was not 100% clear to me (it wasn't clear what file to edit)
- Call to `new cart` used two different alignments. Edited it so that it was homogeneous (feel free to edit it in a different way)
=> Simplify instructions in Cart demo + make homogeneous calls

.github/workflows/lint.yml, .github/workflows/tests.yml
GitHub was telling us that we are reaching our limit for CI/CD systems, this should ease that a bit.
=> Run CI only for master branches

packages/cli/src/commands/new/command.ts, packages/cli/src/commands/new/entity.ts, packages/cli/src/commands/new/event.ts, packages/cli/src/commands/new/project.ts, packages/cli/src/commands/new/type.ts, packages/cli/src/services/config-service.ts, packages/cli/src/services/project-initializer.ts, packages/framework-core/test/services/event-store.test.ts, packages/framework-core/test/services/raw-events-parser.test.ts, packages/framework-core/test/services/read-model-store.test.ts, tsconfig.eslint.json
This PR ran `check-all-the-things` and uncovered some quirks we had in our code. Also added a file that was needed for ESLint to work properly.
=> Style issues

.github/workflows/docs.yml
I have no idea if this works, only way to test it is by merging it ¯\\\_(ツ)\_/¯
=> ci: Add GitHub action for docs

docs/documentation/README.md
The changes of this PR fix the broken links of the docs/documentation/README.
Keep up with the amazing work!
=> Fix broken README links

package.json, packages/framework-core/package.json, yarn.lock
This PR fixes tests on windows
=> build: Fix windows tests command

packages/framework-core/src/booster-register-handler.ts
This PR is actually to trigger npm publishing
=> fix: Typo on error

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, docs/documentation/README.md, docs/documentation/_03-commands.md, docs/documentation/_04-events.md, docs/documentation/_05-entities.md, docs/documentation/_06-read-models.md, docs/documentation/_07-auth.md, docs/documentation/_08-deployment.md, docs/documentation/_09-rest-api.md
- Point broken link to boostercloud GitHub repo
- Fix broken links in docs
- Add PR template
No testing required
=> [BOOST-507] fix broken link to boostercloud GitHub org 2

package.json, packages/framework-core/src/services/graphql/graphql-type-informer.ts, yarn.lock
Upgrade Minimist dependency in the project to fix vulnerability issue when using Minimist version below 0.2.1
https://github.com/boostercloud/booster/network/alert/yarn.lock/minimist/open
=> fix: upgrade minimist

packages/cli/src/templates/entity.ts
Fix function name in entity template
Documentation PR that will contain the change
https://github.com/boostercloud/docs/pull/5/files
- updated function name
=> fix: entity reducer function name

packages/cli/src/services/provider-service.ts, packages/framework-core/src/booster-auth.ts, packages/framework-core/src/booster-graphql-dispatcher.ts, packages/framework-core/src/booster-read-model-dispatcher.ts, packages/framework-core/src/booster-register-handler.ts, packages/framework-core/src/booster-subscribers-notifier.ts, packages/framework-core/src/booster.ts, packages/framework-core/src/services/event-store.ts, packages/framework-core/src/services/raw-events-parser.ts, packages/framework-core/src/services/read-model-store.ts, packages/framework-core/test/booster-auth.test.ts, packages/framework-core/test/booster-graphql-dispatcher.test.ts, packages/framework-core/test/booster-register-handler.test.ts, packages/framework-core/test/services/event-store.test.ts, packages/framework-core/test/services/raw-events-parser.test.ts, packages/framework-core/test/services/read-model-store.test.ts, packages/framework-provider-aws/src/index.ts, packages/framework-provider-local/src/index.ts, packages/framework-types/src/provider.ts
Refactor the ProviderLibrary type as a scoped interface
- Refactor ProviderLibrary as interface 
- Refactor all the ProviderLibrary calls.
=> Refactor the ProviderLibrary type as a scoped interface

packages/cli/src/templates/command.ts, packages/framework-integration-tests/integration/fixtures/commands/ChangeCart.ts, packages/framework-integration-tests/integration/fixtures/commands/ChangeCartWithFields.ts
Updating CLI new command template to fix potential compilation issues
- Update Command template
- Update tests
=> [FIX] update CLI command template

.github/workflows/integration-tests.yml
=> Delete run check creation

.github/workflows/integration-tests.yml
=> Revert delete create run check

.github/PULL_REQUEST_TEMPLATE.md
As we're reworking the documentation to live within this same repository
<Changes made>
=> Fixed the pull request template

packages/framework-integration-tests/integration/providers/aws/event-handlers.integration.ts, packages/framework-integration-tests/integration/providers/aws/utils.ts, yarn.lock
Test that event handlers are able to trigger other events - This is a provider-specific test due to the fact that the `events store` needs to be checked
- A test is added to check event handler
- A function added to provider utils to retrieve events based on an entity ID
- A function added to provider utils to retrieve auth token for authorized requests
=> Test event handlers

packages/framework-integration-tests/integration/end-to-end/cart.integration.ts, packages/framework-integration-tests/integration/providers/aws/auth.integration.ts, packages/framework-integration-tests/integration/providers/aws/event-handlers.integration.ts, packages/framework-integration-tests/integration/providers/aws/utils.ts
Adds a test to verify that a reduction in an Entity is applied due to an event
- Refactor the createAdmin function to become more flexible with user roles
- Add test to check entity reducers
=> BOOST-467 event reduction into entities

docs/README.md
This PR adds the headings for the Booster architecture sections. It also inlines a reference because using references vs using links is something that may need an agreement as references are a bit harder to handle.
=> Add headings for the booster architecture section

packages/framework-integration-tests/integration/providers/aws/entities.integration.ts, packages/framework-integration-tests/integration/providers/aws/utils.ts
Add an integration test that checks that a read model is correctly projecting an entity and generating the corresponding objects in the read model database **(AWS)**.
- A new integration test was added.
- New helper methods were added to query the read model tables.
~- [ ] Updated documentation accordingly~ NOT NEEDED
The test executes two mutations to update the same read model on purpose. I want to check that the same DynamoDB item is updated and no new rows are created.
=> Integration test AWS: Entities projection into read models

docs/README.md
This PR adds some parts of the documentation for the `Command and command handlers` section.
I'll open it as a draft because it is not complete but it can be reviewed/discussed. Next week I'll be on vacations so if some of you can help with the missing parts that would be awesome:
=> Booster architecture commands

docs/README.md
You can see the rendered file [here](https://github.com/boostercloud/booster/blob/808c6e73573bd707e84615bb263057ee35d0741e/docs/README.md)
Filled in documentation with pieces from the old public docs.
Tried mixing the code we previously had on the right with the text and moved some paragraphs into places where they might belong better.
Updated README
=> BOOST-786: update new docs

packages/framework-core/src/booster-read-model-dispatcher.ts, packages/framework-integration-tests/integration/end-to-end/cart.integration.ts, packages/framework-integration-tests/integration/providers/aws/.mocharc.yml, packages/framework-integration-tests/integration/providers/aws/auth.integration.ts, packages/framework-integration-tests/integration/providers/aws/entities.integration.ts, packages/framework-integration-tests/integration/providers/aws/utils.ts, packages/framework-integration-tests/integration/providers/local/setup.ts, yarn.lock
Refactor entities integration tests to attempt reducing failures
- Split promise.all into two different requests
- [n/a] Updated documentation accordingly
=> Refactor: update mutations for entities integration tests

docs/README.md
This PR adds the documentation for the events section
=> Document the events section

docs/README.md
Updated deployment section to be inside the features block
<Changes made>
=> BOOST-794: update deployment section

docs/README.md, packages/framework-integration-tests/src/config/config.ts, packages/framework-integration-tests/src/config/development.ts, packages/framework-integration-tests/src/config/local.ts
Adds documentation about local provider, Booster config and environments and how to run locally
- Config files in integration test package
- Readme.md
=> [DOCS] local provider usage

packages/framework-integration-tests/integration/providers/local/commands.integration.ts, packages/framework-integration-tests/package.json, packages/framework-provider-local/src/index.ts, packages/framework-provider-local/src/library/events-adapter.ts, packages/framework-provider-local/src/services/event-registry.ts, packages/framework-provider-local/test/helpers/event-helper.ts, packages/framework-provider-local/test/library/events-adapter.test.ts, packages/framework-provider-local/test/services/event-registry.test.ts, yarn.lock
Add logic to correctly reduce events into entities and create snapshots
- Implement new functions to notify Booster Core that an event has been stored in the Database
- Add tests
=> Local provider event reduction into entities

docs/README.md
While I was reading the documentation to create a new section, I was applying several corrections in typos, expressions, accuracy, and many other things.
This PR collects all those changes to the "Getting started" section
- ~[ ] Project Builds~
- ~[ ] Project passes tests and checks~
=> [DOCS] Fixes to the getting started section 

docs/README.md
As I read these sections, I was doing small corrections and clarifications
=> Suggestions and changes to "Commands" and "Events" architecture sections

docs/README.md
I finish reading the whole docs before the "Application API" section and these are the final suggestions and fixes
=> Suggestions and changes to "Event handlers", "Entities", and "Read models" architecture sections

docs/README.md
I kept reading docs to have to context for the GraphQL and Apollo documentation and did some changes to the sections named in the PR title
=> Changes to docs: Auth, Cloud Native, Configuration and Environments

docs/README.md
Detailing some steps to run the example better
enhancing the documentation
README file
=> Enhancing README file with notes

docs/CONTRIBUTING.md
Add principles and practices to enable contributors to help us with documenting.
<Changes made>
=> Create Docs Contributing

CONTRIBUTING.md
=> update contributing: add link to create GitHub issues

packages/cli/src/commands/new/command.ts, packages/cli/src/commands/new/entity.ts, packages/cli/src/commands/new/event-handler.ts, packages/cli/src/commands/new/event.ts, packages/cli/src/commands/new/project.ts, packages/cli/src/commands/new/read-model.ts, packages/cli/src/commands/new/type.ts
This PR is a clone of PR #274 because integration tests could not be run on the original one. Refer to that PR for related information and discussion
=> fix(cli): h flag exit error (clone of PR #274)

docs/README.md
=> update docs: add link to contributing guide

docs/README.md
I just rephrased some quotes for more clarity and accuracy.
=> Improvements in the docs intro

docs/README.md
Documentation for read models
Modified the documentation readme.
=> [BOOST-562] read models documentation

docs/README.md, docs/examples/cart-service/part-1-build-and-deploy.md, packages/cli/src/templates/command.ts, packages/framework-core/src/booster-command-dispatcher.ts, packages/framework-core/src/decorators/command.ts, packages/framework-core/src/migrator.ts, packages/framework-core/test/booster-command-dispatcher.test.ts, packages/framework-core/test/decorators/command.test.ts, packages/framework-core/test/migrator.test.ts, packages/framework-integration-tests/integration/fixtures/commands/ChangeCart.ts, packages/framework-integration-tests/integration/fixtures/commands/ChangeCartWithFields.ts, packages/framework-integration-tests/src/commands/ChangeCartItem.ts, packages/framework-integration-tests/src/commands/ConfirmPayment.ts, packages/framework-integration-tests/src/commands/CreateProduct.ts, packages/framework-integration-tests/src/commands/DeleteProduct.ts, packages/framework-integration-tests/src/commands/MoveStock.ts, packages/framework-integration-tests/src/commands/UpdateProduct.ts, packages/framework-integration-tests/src/commands/UpdateShippingAddress.ts, packages/framework-types/src/concepts/command.ts, packages/framework-types/src/envelope.ts, yarn.lock
**Note:** Changes should be actually
```diff
+31
-82
```
The rest are `yarn.lock` changes
In order to maintain API consistency with the rest of the user-implemented functions, we gonna make now the command handlers be a static function. 
* Separated CommandInterface into CommandInterface and CommandClassInterface. 
* CommandInterface has no restrictions, so we making it `unknown`.
* CommandClassInterface restricts the static method to receive a Command
=> Inject command object into handlers

.vscode/launch.json, README.md, packages/framework-integration-tests/integration/end-to-end/setup.ts, packages/framework-integration-tests/integration/providers/aws/functionality/auth.integration.ts, packages/framework-integration-tests/integration/providers/aws/functionality/entities.integration.ts, packages/framework-integration-tests/integration/providers/aws/functionality/event-handlers.integration.ts, packages/framework-integration-tests/integration/providers/aws/functionality/events.integration.ts, packages/framework-integration-tests/integration/providers/aws/functionality/subscriptions.integration.ts, packages/framework-integration-tests/integration/providers/aws/nuke/nuke.integration.ts, packages/framework-integration-tests/integration/providers/aws/nuke/setup.ts, packages/framework-integration-tests/integration/providers/aws/utils.ts, packages/framework-integration-tests/package.json, packages/framework-integration-tests/src/deploy.ts, yarn.lock
I just want to see if Github can run the new integration tests...
=> Integration test fixes

packages/framework-integration-tests/integration/cli/cli.project.integration.ts
Integration tests got broken after it
=> Add assertion for #456

packages/cli/src/commands/new/entity.ts, packages/cli/src/commands/new/event-handler.ts, packages/cli/src/commands/new/read-model.ts, packages/cli/src/common/filenames.ts
Refactor naming generation
Add a new function in a new file
=> Refactor naming generation

CONTRIBUTING.md
Documentation to help contribute
Only documentation
Closes #447
=> add documentation to help contribute

.github/workflows/lint.yml, packages/cli/package.json, packages/framework-core/package.json, packages/framework-integration-tests/package.json, packages/framework-provider-aws-infrastructure/package.json, packages/framework-provider-aws/package.json, packages/framework-provider-azure-infrastructure/package.json, packages/framework-provider-azure/package.json, packages/framework-provider-kubernetes-infrastructure/package.json, packages/framework-provider-kubernetes/package.json, packages/framework-provider-local-infrastructure/package.json, packages/framework-provider-local/package.json, packages/framework-types/package.json, scripts/check-all-the-things.ps1, scripts/check-all-the-things.sh
Rename all lint-related command using suggested format: `lint:check` and `link:fix.`
resolves #96 
- Packages.json files
- Github workflow for lint
- Bash and powershell scripts
=> Update all files related to linting commands

docs/README.md
Deploy documentation. Fixes #454 
Add a note for deploy documentation
=> Document everything in project root  is deployed

scripts/check-all-the-things.sh
The line was getting too long to read.
Broke it into multiple lines for easier readability.
~~- [] Updated documentation accordingly~~
-
=> break into multiple lines for easier readability

docs/README.md
Add Git prerequisite to documentation
<Changes made> 
Fixes #457
=> Add Git prerequisite

packages/framework-integration-tests/integration/providers/local/read-models.integration.ts
A new file introduced in an "automatic merge" missed some changes in the way local tests were refactored, causing errors.
* Fixed the breaking tests
~- [ ] Updated documentation accordingly~
=> Fixed local integration tests

packages/framework-provider-local-infrastructure/package-lock.json
This PR is a small fix due to an issue with a previous merge in the `package-lock.json` inside `framework-provider-local-infrastructure`
=> fix wrong lock file

CONTRIBUTING.md
Upon popular request, I've added some code guidelines to `CONTRIBUTING.md`, feel free to submit your suggestions too!
=> Added some code guidelines

docs/README.md, packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/application-stack.ts
I've reopened PR #563 here to fix a bad rebase, there are no code changes.
=> feature: Print the full GraphQL endpoint after a successful deploy

CONTRIBUTING.md
Information update in CONTRIBUTING.md
<Changes made>
=> Doc: Update contributing file

packages/rocket-batch-file-process-aws-infrastructure/.eslintignore, packages/rocket-batch-file-process-aws-infrastructure/.mocharc.yml, packages/rocket-batch-file-process-aws-infrastructure/.npmignore, packages/rocket-batch-file-process-aws-infrastructure/README.md, packages/rocket-batch-file-process-aws-infrastructure/package.json, packages/rocket-batch-file-process-aws-infrastructure/src/batch-file-processing.ts, packages/rocket-batch-file-process-aws-infrastructure/src/entities/file.ts, packages/rocket-batch-file-process-aws-infrastructure/src/events/file-added.ts, packages/rocket-batch-file-process-aws-infrastructure/src/index.ts, packages/rocket-batch-file-process-aws-infrastructure/src/lambdas/index.ts, packages/rocket-batch-file-process-aws-infrastructure/src/lambdas/package.json, packages/rocket-batch-file-process-aws-infrastructure/tsconfig.eslint.json, packages/rocket-batch-file-process-aws-infrastructure/tsconfig.json
Add new Rocket:
- Create new source Bucket with event notifications.
- Create new Lambda (triggered by event notification) that will persist split the file with a given N size lines passed in the params it will also persist a new event for each new file added
- These new files will be persisted in a new Staging bucket
Add new package for new rocket + upadte lerna.json and packge.json with new package.
=> Add New rocket to process batch files

docs/README.md
These are some guidelines that might be useful for people testing a Booster application. It helps also fixing some of the errors from https://github.com/boostercloud/booster/issues/627
Add docs about how to test a Booster application
=> [Docs] - Testing Booster applications

packages/framework-provider-kubernetes/src/index.ts, packages/framework-provider-kubernetes/src/library/events-adapter.ts, packages/framework-provider-kubernetes/src/services/event-registry.ts, packages/framework-provider-kubernetes/src/services/read-model-registry.ts
Initial work to do mutations and queries. In the current implementation we are able to perform simple mutations and perform queries by ID. There are a lot of stuff to polish!!!
<Changes made>
=> [WIP] adjusted the methods to perform simple queries and mutations

package-lock.json, packages/framework-provider-kubernetes-infrastructure/src/helpers/promises.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/dapr-manager.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/index.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/k8s-sdk/k8s-management.ts, packages/framework-provider-local-infrastructure/src/index.ts
Copy paste, but will be fixed by #684
=> Change promise.all to promises helpers in K8s

package-lock.json, packages/framework-provider-kubernetes-infrastructure/src/helpers/promises.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/dapr-manager.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/index.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/k8s-sdk/k8s-management.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/runtime/index.ts, packages/framework-provider-kubernetes/package.json, packages/framework-provider-kubernetes/src/index.ts, packages/framework-provider-kubernetes/src/library/events-adapter.ts, packages/framework-provider-kubernetes/src/library/read-model-adapter.ts, packages/framework-provider-kubernetes/src/services/event-registry.ts, packages/framework-provider-kubernetes/src/services/read-model-registry.ts, packages/framework-provider-local-infrastructure/src/index.ts
scafolding for K8s provider runtime
<Changes made>
=> k8s runtime scafolding

packages/framework-provider-kubernetes-infrastructure/src/infrastructure/helm-manager.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/templates/statestore.ts
Fixed the problem during the first time deploy, the deploy wasn't checking the status of the helm repos and the statestore template was not using the latest version.
=> Polish first time installation problems

packages/framework-provider-kubernetes-infrastructure/src/infrastructure/runtime/index.ts, packages/framework-provider-kubernetes/src/library/api-adapter.ts, packages/framework-provider-kubernetes/src/library/graphql-adapter.ts
return the correct body in k8s implementation
- update Express server handler
- update GraphQL handler
=> fix graphql body bug. Return application/json content type

packages/framework-provider-kubernetes/package.json, packages/framework-provider-kubernetes/src/services/event-registry.ts
generate a more appropriate Redis key to store events and snapshots
- how we generate the key
=> generate a redis key for events and snapshots

packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/application-stack.ts
The returned graphqlURL is wrong.
Fix graphqlURL
=> Fix: fix graphqlURL

packages/framework-provider-kubernetes-infrastructure/src/infrastructure/dapr-manager.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/deploy-manager.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/index.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/templates/booster-app-template.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/templates/statestore.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/templates/template-types.ts
added username and password to booster pods for runtime
=> added db info to runtime

packages/framework-provider-kubernetes/package.json, packages/framework-provider-kubernetes/src/services/event-registry.ts, packages/framework-provider-kubernetes/src/services/redis-adapter.ts
create a Redis class to communicate with Redis server directly
- Create RedisAdapter class with keys method uncompleted
=> start to create redis adapter

packages/framework-provider-kubernetes-infrastructure/src/infrastructure/dapr-manager.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/deploy-manager.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/index.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/templates/booster-app-template.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/templates/template-types.ts, packages/framework-provider-kubernetes/package.json, packages/framework-provider-kubernetes/src/library/events-adapter.ts, packages/framework-provider-kubernetes/src/services/event-registry.ts, packages/framework-provider-kubernetes/src/services/redis-adapter.ts
- Added the dbHost into the K8s Booster template
- Started to work on mutations
=> working on mutations for k8s provider

docs/README.md
The authentication feature has beed removed from the core and now the recommended option is to use the Authentication Rocket.
Update the authentication section from the documentation and refer to the Authentication Rocket.
=> Doc: Update auth section

packages/framework-provider-kubernetes/src/index.ts, packages/framework-provider-kubernetes/src/library/events-adapter.ts, packages/framework-provider-kubernetes/src/library/graphql-adapter.ts, packages/framework-provider-kubernetes/src/library/read-model-adapter.ts, packages/framework-provider-kubernetes/src/runtime/index.ts, packages/framework-provider-kubernetes/src/services/read-model-registry.ts
store and fetch readModels into Redis
- store readModel into Redis
- fetch readModel into Redis
- fix search readModel
- call event processor after event store
=> store readModel into Redis via Dapr. fetch readModel via Redis

packages/cli/src/services/project-initializer.ts, packages/cli/src/templates/project/mocharc-yml.ts, packages/cli/src/templates/project/package-json.ts, packages/cli/test/commands/new/project.test.ts, packages/cli/test/services/project-initializer.test.ts, packages/framework-integration-tests/integration/cli/cli.project.integration.ts, packages/framework-integration-tests/integration/fixtures/cart-demo/.mocharc.yml, packages/framework-integration-tests/integration/fixtures/cart-demo/package.json
Add `.mocharc.yml` file when `boost new:project app` and add `BOOSTER_ENV` to test script in `package.json`.
Closes #627
=> Fix/627 Add mocha file + test env variables

docs/README.md
This pull request tries to **clarify a little bit better some of the advantages of using Booster regarding the application infrastructure.**
- Modified `Why use Booster?` to clarify some of the advantages regarding the deployed application infrastructure.
=> Documentation: Booster infrastructure advantages

packages/framework-provider-kubernetes/src/library/events-adapter.ts, packages/framework-provider-kubernetes/src/services/read-model-registry.ts
fixed read model queries for multiple elements
=> fixed query multiple items in readmodels

docs/README.md
There is currently no reference to the Booster Rockets in the documentation.
Add a list with the current BoosterRockets
=> Doc: Add Booster Rockets list

docs/README.md
This PR includes **some small improvements on the  "Booster architecture" section.**
- Clarified some subsections.
- Rearranged some file lines to improve writer readability.
- Fixed some minor issues in the document.
=> Documentation: Small improvements in "Booster architecture" section

docs/README.md
This PR includes **some small improvements on the  "GraphQL API" subsection** in the "Features" section.
- Fixed imports in Apollo Client code snippets.
- Rearranged some file lines to improve writer readability.
- Fixed some minor issues in the document.
=> Documentation: Small improvements in the "GraphQL API" section

docs/README.md
This PR **includes some small improvements on the "Debugging and testing Booster applications" section.**
- Changed paragraph organization.
- Improved word format.
- Clarified some sentences and explanations.
=> Documentation: Small improvements in the "Debugging and testing Booster applications" section.

docs/README.md
This PR tries to improve the Rockets section
=> doc: Update rockets section

packages/framework-core/src/helpers/retrier.ts, packages/framework-core/src/services/read-model-store.ts, packages/framework-core/test/helpers/retrier.test.ts, packages/framework-core/test/services/read-model-store.test.ts, packages/framework-integration-tests/integration/end-to-end/load/optimistic-concurrency-on-read-models.integration.ts, packages/framework-integration-tests/src/read-models/products-by-sku.ts, packages/framework-provider-aws/src/library/read-models-adapter.ts, packages/framework-provider-aws/test/library/read-models-adapter.test.ts, packages/framework-types/src/concepts/read-model.ts, packages/framework-types/src/errors.ts, packages/framework-types/src/provider.ts
Reverts boostercloud/booster#754
Apply this again
=> Revert "Revert "Implement optimistic concurrency for read models""

docs/README.md
Explain how to create a new rocket
Replace "Infrastructure extensions" section by "Create your own rocket" section.
=> doc: Document how to create a rocket

packages/framework-provider-kubernetes-infrastructure/src/infrastructure/dapr-manager.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/deploy-manager.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/k8s-sdk/k8s-management.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/templates/statestore-role-binding.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/templates/statestore-role.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/templates/statestore.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/templates/template-types.ts, packages/framework-provider-kubernetes-infrastructure/test/infrastructure/deploy-manager.test.ts
This PR allows us to use the secrets to get the state store password instead of adding it as plain text in the state store file
=> Use Kubernetes secrets to get the password for the state store. 

docs/README.md
Just added a bit of information about `Homebrew` and `Chocolatey` package managers so users can install them if they don't haven't already.
Added `Homebrew` and `Chocolatey` links on the `nodejs` install section.
If you feel there is something we can improve in the installing section, please feel free of sharing your thoughts here.
=> Improve installing nodejs section

docs/README.md
Enhance documentation
- Update Readme file
- [x ] Project passes tests and checks
- [x ] Updated documentation accordingly
=> modify introduction in doc

CONTRIBUTING.md, docs/chapters/01_introduction.md, docs/chapters/02_getting-started.md, docs/chapters/03_booster-architecture.md, docs/chapters/04_features.md, docs/chapters/05_going-deeper.md, docs/chapters/06_testing-booster-applications.md, docs/custom.css, docs/index.html
I created a docsify plugin to add the "edit on github" button implicitly.
=> doc: Create "edit on github" plugin

CONTRIBUTING.md, README.md
Update documentation link
-README
-CONTRIBUTING
- [x ] Project passes tests and checks
- [x ] Updated documentation accordingly
=> update doc link to docs.booster.cloud

docs/custom.css, docs/index.html
Remove the hamburger button for large screens and align the "edit on github" button to the right.
=> doc: remove hamburger button for large screens

CONTRIBUTING.md, docs/custom.css
Some header size are too small.
Fix some header sizes.
=> doc: Fix header size

CONTRIBUTING.md, docs/index.html
=> Doc: Add seo plugin

docs/custom.css, docs/index.html
Change background colors of alerts for light theme.
=> doc: Fix alert colors

CONTRIBUTING.md
Improve test documentation by describing how contributors must pass tests locally before creating a PR.
=> doc: Improve test documentation for external contributors

docs/chapters/07_frequently-asked-questions.md, docs/sidebar.md
FAQ section is missing
Add FAQ section
=> doc: Add FAQ section

packages/framework-core/src/services/graphql/graphql-query-generator.ts, packages/framework-core/src/services/graphql/graphql-type-informer.ts, packages/framework-core/test/services/graphql/graphql-query-generator.test.ts, packages/framework-core/test/services/graphql/graphql-type-informer.test.ts
Added some improvement to the GraphQL generator method following some suggestions that were not included in the previous PR.
* Improved function to get extended types, now it's recursive
* Improved some conditions
* Rename some functions for better understanding
=> GraphQL improvements

docs/chapters/04_features.md
This PR corrects the uri indicated in the httpLink for the Apollo Client.
=> doc: Fix httpLink url

docs/index.html
We want both the landscape and the documentation website to be under the same Google Analytics
Updating the universal Analytics id
=> doc: update Universal Analytics id

README.md
I'd love to hear the team's feedback on this ;-)
<Changes made>
=> Update of the README.md file following the changes of the main project website

docs/chapters/04_features.md
This PR integrates **improvements on the `Authentication and Authorization` section,** clarifying some of the aspects of the feature, reorganising the text to be easier to understand and fixing some mistakes.
- Restructured `Authentication and authorization` section.
- Improved `Custom authentication` section, explaining a little bit better some of the aspects of the feature and fixing some misleading explanations or orthographic mistakes.
=> Documentation: Authentication and Authorization improvements

docs/chapters/02_getting-started.md
I've added the [video for the creation of the AskMe app](https://www.youtube.com/watch?v=C4K2M-orT8k) in the examples section.
=> docs: Add AskMe example video

packages/framework-provider-local/package.json, packages/framework-provider-local/src/library/events-adapter.ts, packages/framework-provider-local/src/services/event-registry.ts, packages/framework-provider-local/test/helpers/event-helper.ts, packages/framework-provider-local/test/library/events-adapter.test.ts, packages/framework-provider-local/test/services/event-registry.test.ts
Fix Local Provider event methods and add some unit tests
- Fix event methods for Local Provider
- Add some unit tests for Local Provider
=> Local Provider - event methods review

package-lock.json, packages/cli/src/services/project-checker.ts, packages/cli/test/services/dependencies.test.ts, packages/cli/test/services/script-service.test.ts, packages/framework-core/test/services/event-store.test.ts, packages/framework-core/test/services/raw-events-parser.test.ts, packages/framework-core/test/services/read-model-store.test.ts, packages/framework-provider-aws-infrastructure/src/infrastructure/nuke.ts, packages/framework-provider-aws-infrastructure/test/infrastructure/deploy.test.ts, packages/framework-provider-aws-infrastructure/test/infrastructure/nuke.test.ts, packages/framework-provider-aws/src/library/events-adapter.ts, packages/framework-provider-aws/test/library/events-adapter.test.ts, packages/framework-provider-kubernetes/src/library/read-model-adapter.ts, packages/framework-provider-kubernetes/src/runtime/index.ts, packages/framework-provider-kubernetes/src/services/redis-adapter.ts
Ran `./scripts/check-all-the-things.sh` and ESLint made these changes. Merging right away.
=> style: Stylistic changes caught by ESLint

packages/framework-provider-local/src/index.ts
=> Fixes by ESLint automatic action

packages/framework-core/src/services/graphql/graphql-query-generator.ts
Reverts boostercloud/booster#868 to publish it on a new release
=> Revert "include custom object types like enums"

docs/index.html
=> fix: fix typo

package-lock.json, packages/framework-provider-kubernetes-infrastructure/package.json, packages/framework-provider-kubernetes/package.json, packages/framework-provider-local-infrastructure/package.json, packages/framework-provider-local-infrastructure/src/index.ts
Using the local provider from a web browser was giving CORS errors. This PR fixes that
- ~[ ] Updated documentation accordingly~
=> Enable CORS in local provider

docs/chapters/02_getting-started.md
fix #977 fix / Getting Started / Your first Booster app in 10 minutes / wrong ReadModel joinKey
change joinKey from `postId` to `id`
=> fix(docs): wrong ReadModel joinKey

packages/framework-core/src/services/read-model-store.ts, packages/framework-provider-aws/src/library/read-models-adapter.ts, packages/framework-provider-aws/test/library/read-models-adapter.test.ts, packages/framework-provider-azure/src/constants.ts, packages/framework-provider-azure/src/library/read-model-adapter.ts, packages/framework-provider-azure/test/library/read-model-adapter.test.ts, packages/framework-types/src/concepts/read-model.ts
Support optimistc concurrency on Azure Provider
- Update tests
- Add optimisticConcurrencyValue to ReadModelInterface
- Add/Update store read models method to handle concurrency with ReadModelInterface
=> Azure optimistic concurrency

package-lock.json, packages/framework-core/src/services/graphql/graphql-type-informer.ts, packages/framework-core/test/services/graphql/graphql-type-informer.test.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/helper/az-cli-helper.ts, packages/framework-provider-kubernetes/src/services/redis-adapter.ts
Resolves issue #986 
A command can now have more than one field with the same custom class type.
=> fix: Commands with 2 or more fields of the same custom class throws an error

packages/framework-core/src/index.ts
Export the RegisterHanlder to be available for the Rockets
Export the RegisterHanlder class
=> Export RegisterHanlder

packages/framework-provider-azure-infrastructure/src/infrastructure/synth/terraform-containers.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/synth/terraform-cosmosdb-sql-database.ts
Reduce from 10.000 to 2.000 the default RU/s for CosmosDB
- ~[ ] Updated documentation accordingly~
=> Reduce Azure CosmosDB RUs

packages/cli/src/services/logger.ts, packages/framework-core/src/booster-logger.ts, packages/framework-core/test/booster-command-dispatcher.test.ts, packages/framework-core/test/booster-event-dispatcher.test.ts, packages/framework-core/test/booster-logger.test.ts, packages/framework-core/test/booster-read-model-reader.test.ts, packages/framework-core/test/helpers/logger-helper.ts, packages/framework-core/test/migrator.test.ts, packages/framework-provider-aws-infrastructure/test/index.test.ts, packages/framework-provider-aws/test/library/events-adapter.test.ts, packages/framework-provider-aws/test/library/read-models-adapter.test.ts, packages/framework-provider-aws/test/library/read-models-searcher-adapter.test.ts, packages/framework-provider-aws/test/library/subscription-adapter.test.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/helper/logger.ts, packages/framework-provider-azure-infrastructure/src/logger.ts, packages/framework-provider-azure/test/helpers/query-helper.test.ts, packages/framework-provider-azure/test/library/events-adapter.test.ts, packages/framework-provider-azure/test/library/events-searcher-adapter.test.ts, packages/framework-provider-azure/test/library/read-model-adapter.test.ts, packages/framework-provider-kubernetes-infrastructure/test/infrastructure/K8sManagement.test.ts, packages/framework-provider-kubernetes-infrastructure/test/infrastructure/dapr-manager.test.ts, packages/framework-provider-kubernetes-infrastructure/test/infrastructure/deploy-manager.test.ts, packages/framework-provider-kubernetes-infrastructure/test/infrastructure/helm-manager.test.ts, packages/framework-provider-local/test/library/events-adapter.test.ts, packages/framework-provider-local/test/library/read-model-adapter.test.ts, packages/framework-types/src/logger.ts
The current Logger didn't include the `warn` option. In this PR we are adding that option to the Logger
- [x ] Project passes tests and checks
=> added warning to logger

.github/workflows/integration-tests.yml, .github/workflows/lint.yml, .github/workflows/publish.yml, .github/workflows/tests.yml, package-lock.json, packages/application-tester/src/token-helper.ts, packages/framework-core/src/booster-graphql-dispatcher.ts, packages/framework-core/src/booster-token-verifier.ts, packages/framework-core/test/booster-token-verifier.test.ts, packages/framework-integration-tests/integration/provider-unaware/end-to-end/events.integration.ts, packages/framework-integration-tests/src/config/config.ts, packages/framework-types/src/errors.ts
* Throw specific token error if expired or notBefore exception
=> Throw specific token error if expired or notBefore exception

package-lock.json, packages/framework-integration-tests/integration/provider-unaware/end-to-end/read-models.integration.ts, packages/framework-provider-local/src/library/read-model-adapter.ts, packages/framework-provider-local/src/library/searcher-adapter.ts, packages/framework-provider-local/test/library/read-model-adapter.test.ts, packages/framework-provider-local/test/library/searcher-adapter.test.ts
Local Provider Search method use AND as the default WHERE operator
=> Local Provider Search method use AND as the default WHERE operator

package-lock.json, packages/framework-provider-local-infrastructure/package.json, packages/framework-provider-local-infrastructure/src/index.ts, packages/framework-provider-local-infrastructure/src/scheduler.ts, packages/framework-provider-local/src/index.ts, packages/framework-provider-local/src/library/scheduled-adapter.ts
Add Schedule commands for Local Provider
=> Add Scheduled Commands for Local Provider

packages/framework-core/src/booster-token-verifier.ts, packages/framework-integration-tests/src/config/config.ts, packages/framework-types/src/concepts/projection-metadata.ts, packages/framework-types/src/concepts/token-verifier-config.ts
Apply https://github.com/boostercloud/booster/pull/1067 fixes on v0.26 branch
=> Promisified public key field in the token verifier config

packages/cli/src/templates/project/package-json.ts, packages/cli/test/fixtures/mock_project/package.json
Cli module templates needs to be updated to use the new GraphQL Generator
=> Update package.json template

docs/chapters/02_getting-started.md
Missing documentation updates on latest changes.
=> Documentation updates on latest changes

packages/framework-provider-local/src/index.ts, packages/framework-provider-local/src/library/read-model-adapter.ts, packages/framework-provider-local/src/services/read-model-registry.ts, packages/framework-provider-local/test/library/read-model-adapter.test.ts, packages/framework-provider-local/test/services/read-model-registry.test.ts
Add delete read model to the Local provider
=> Add delete read model to the Local provider

packages/framework-core/src/services/raw-events-parser.ts, packages/framework-core/test/services/raw-events-parser.test.ts
Added better error handling to the RawEventsParser class, as well as a test case
=> Error handling in event processing

packages/framework-core/src/services/event-store.ts
Migration should be run even if there are no reductions to be done. Moving the migration method to be run after loading the latest snapshot.
=> Migrate while loading latest snapshot

docs/chapters/04_features.md
Fix errors in token verifiers signatures
=> Minor documentation fix

packages/metadata-booster/src/metadata-extractors.ts
There were some cases where Classes' metadata was created as Array.
Also, there were other cases where modules tried to import themselves.
=> Fix metadata creation for some types

package-lock.json, packages/framework-core/src/services/pub-sub/read-model-pub-sub.ts, packages/framework-provider-local-infrastructure/src/index.ts
Fixed logic of includes filter for subscriptions
=> fix(core): includes filter logic

packages/cli/src/templates/project/package-json.ts
=> Add caret to TS version

.github/workflows/publish.yml, common/config/rush/version-policies.json
Fixed some issues in the publishing workflow
=> Update package publishing

README.md
Fixes "Build Status" and "Integration tests" badges
- "Build Status" uses "master" branch as the default
- "Integration tests" badge has a different/changed path
Fixed path to GitHub actions workflow and added `?ref=main` to use main branch for "Build Status" badge
=> fix(docs): Fix readme file badges

packages/framework-core/src/index.ts, packages/framework-integration-tests/src/read-models/data-migrations-read-model.ts
Export `BoosterDataMigrationEntity` entity
- Export entity on index file
=> Export BoosterDataMigrationEntity

common/config/rush/pnpm-lock.yaml, common/config/rush/version-policies.json
This PR makes `rush change --verify` to work properly and `rush change` to prompt for version changes.
=> fix(ci): Remove nextBump to force asking for changes

packages/framework-core/src/booster-read-models-reader.ts, packages/framework-core/test/booster-read-model-reader.test.ts
Run the SchemaMigrations for ReadModels also on fetch/search actions.
- Add tests
- Call ReadModelSchemaMigrator on fetch and search methods
=> Migrate on ReadModel Find and Search

.github/workflows/changes-check.yml, .github/workflows/integration-tests.yml, .github/workflows/lint.yml, .github/workflows/publish.yml, .github/workflows/tests.yml, common/changes/@boostercloud/framework-core/integration-1172_2022-11-17-18-06.json, common/config/rush/pnpm-lock.yaml, packages/framework-core/src/index.ts, packages/framework-integration-tests/src/read-models/data-migrations-read-model.ts
This is an integration PR for PR #1172. Visit the original PR for further information.
=> Integration branch for Export DataMigrationEntity (#1172)

common/changes/@boostercloud/framework-core/doc-effect-types_2022-12-02-12-39.json, common/config/rush/pnpm-lock.yaml, packages/application-tester/src/effect/index.ts, packages/framework-types/src/effect/index.ts
With #1208 we've introduced some parts of effect-ts to be able to work more effectively in the codebase. This PR documents the reexports in order to get up and running with this style of writing code.
=> doc(framework-types): Document effect-ts reexports

packages/framework-provider-local-infrastructure/src/index.ts, packages/framework-provider-local-infrastructure/src/infrastructure-rocket.ts
Add port to mountStack for local rockets.
=> Add port to mountStack for local rockets

.github/workflows/changes-check.yml, .github/workflows/codesee-arch-diagram.yml, .github/workflows/integration-tests.yml, .github/workflows/lint.yml, .github/workflows/tests.yml, README.md, common/changes/@boostercloud/framework-core/integration-1182_2022-12-12-18-18.json
Integration branch for PR #1182
=> Integration branch for PR #1182

common/config/rush/pnpm-lock.yaml, website/docs/01_introduction.md, website/docs/02_getting-started/coding.mdx
This PR adds minor improvements to the "Get Started" section, to make it easier to read and understand.
=> Documentation: Minor improvements in format and content to the "Get Started" section

.github/workflows/codesee-arch-diagram.yml, README.md, common/changes/@boostercloud/framework-core/integration-next-patch_2022-12-19-17-40.json
=> Integration branch for #1112

.github/workflows/wf_publish-docs.yml, website/README.md
=> [Feature-1243] Publish docs only on change

common/changes/@boostercloud/framework-core/support_many_rockets_2023-02-13-11-39.json, common/config/rush/pnpm-lock.yaml, packages/framework-core/src/booster-rocket-dispatcher.ts, packages/framework-provider-aws/src/index.ts, packages/framework-provider-aws/src/library/rocket-adapter.ts, packages/framework-provider-aws/src/setup.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/index.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/rockets/rocket-builder.ts, packages/framework-provider-azure/src/index.ts, packages/framework-provider-azure/src/library/rocket-adapter.ts, packages/framework-provider-kubernetes/src/index.ts, packages/framework-provider-kubernetes/src/library/rocket-adapter.ts, packages/framework-provider-local/src/index.ts, packages/framework-provider-local/src/library/rocket-adapter.ts, packages/framework-types/src/provider.ts, packages/framework-types/src/rockets.ts
* Local Provider: 
* Require calls to BoosterRocketDispatcher to include the field BOOSTER_ROCKET_FUNCTION_ID with the rocket_id
* Use of environment variables to set the rocket_id as a fallback if request doesn't include the expected field
* Azure Provider:
* Fix `deploy` command for zip rockets
=> Support multiple rockets

website/docs/02_getting-started/coding.mdx
quick PR fixing a broken link in the documentation 
One line PR ¯\_(ツ)_/¯
=> fixing broken link in documentation

.github/actions/build/action.yml, common/changes/@boostercloud/framework-core/migrate_read_model_when_api_search_2_2023-02-18-18-11.json, packages/framework-core/src/booster-read-models-reader.ts, packages/framework-core/src/booster.ts, packages/framework-types/src/searcher.ts, packages/framework-types/test/searcher.test.ts
FIX Migrate ReadModels when searcher with Booster.readModel
=> Migrate read model when api search

.github/actions/build/action.yml, common/changes/@boostercloud/framework-core/fix-notifications-integ-tests_2023-02-17-17-47.json, common/config/rush/pnpm-lock.yaml, packages/framework-integration-tests/integration/provider-unaware/functionality/notifications.integration.ts, packages/framework-integration-tests/src/commands/abandon-cart.ts, packages/framework-integration-tests/src/commands/flush-notifications.ts, packages/framework-integration-tests/src/entities/cart.ts
=> fix: integration tests for notification events

CONTRIBUTING.md
Fixed the commands in our contributing guide
=> doc: Fix unit tests commands in CONTRIBUTING

common/changes/@boostercloud/framework-core/test-added-tests-for-partition-key-generation-functions_2023-02-27-17-42.json, packages/framework-provider-aws/test/library/keys-helper.test.ts, packages/framework-provider-azure/src/library/partition-keys.ts, packages/framework-provider-azure/test/library/partition-keys.test.ts
Added missing tests for partition key generation functions for AWS and Azure providers
~- [ ] Updated documentation accordingly~
=> Added tests for partition key generation functions

website/src/pages/ask-me.tsx, website/src/styles/pages/booster-chat.css
=> Added beta disclaimer to the ask-me page in the docs

website/src/components/BoosterChat/BoosterChat.tsx, website/src/theme/NavbarItem/ComponentTypes.tsx, website/src/theme/NavbarItem/CustomNavbarItem.tsx, website/src/theme/chat-service.ts
Reverts boostercloud/booster#1368
=> Revert "Reset changes and fix import"

website/src/components/BoosterChat/BoosterChat.tsx
Less redundancy. Also looking better in mobile.
=> Update Ask AI copy

website/src/theme/chat-service.ts
=> Add new AskToAI service URL

website/README.md, website/docs/10_going-deeper/infrastructure-providers.mdx
Also changed the readme for the site from `yarn` to `npm`, which is what we use in the pipeline.
=> Updated docs for azure provider setup to keep it up with API changes.

website/docs/10_going-deeper/rockets.mdx
Updated the rockets documentation, adding a guide to writing new decorators using singleton objects to hold the metadata.
=> Updated rockets documentation

common/changes/@boostercloud/framework-core/local_subscriptions_2023-04-20-19-04.json, common/config/rush/pnpm-lock.yaml, packages/application-tester/package.json, packages/framework-integration-tests/package.json, packages/framework-provider-local-infrastructure/package.json, packages/framework-provider-local/package.json, packages/framework-provider-local/src/index.ts, packages/framework-provider-local/src/library/connections-adapter.ts, packages/framework-provider-local/src/library/events-search-adapter.ts, packages/framework-provider-local/src/library/graphql-adapter.ts, packages/framework-provider-local/src/library/read-model-adapter.ts, packages/framework-provider-local/src/library/subscription-adapter.ts, packages/framework-provider-local/src/library/web-socket-server-adapter.ts, packages/framework-provider-local/src/paths.ts, packages/framework-provider-local/src/services/graphql-service.ts, packages/framework-provider-local/src/services/web-socket-registry.ts, packages/framework-provider-local/test/library/events-adapter.test.ts, packages/framework-provider-local/test/library/events-search-adapter.test.ts, packages/framework-provider-local/test/library/graphql-adapter.test.ts, packages/framework-provider-local/test/library/read-model-adapter.test.ts, packages/framework-provider-local/test/services/event-registry.test.ts, packages/framework-types/src/envelope.ts
This PR add **Local** subscriptions to Booster.
* Local infrastructure needed for Subscriptions
* Local logic needed for Subscriptions
=> Local subscriptions

common/changes/@boostercloud/framework-core/add_regex_filters_2023-03-15-14-15.json, common/config/rush/pnpm-lock.yaml, packages/framework-core/src/services/graphql/query-helpers/graphql-query-filter-arguments-builder.ts, packages/framework-core/src/services/pub-sub/read-model-pub-sub.ts, packages/framework-core/test/services/graphql/graphql-query-generator.test.ts, packages/framework-integration-tests/integration/provider-unaware/end-to-end/read-models.integration.ts, packages/framework-provider-azure/src/helpers/query-helper.ts, packages/framework-provider-local/src/library/searcher-adapter.ts, packages/framework-types/src/searcher.ts, website/docs/06_graphql.md
Add `regex` and `iRegex` filters to Azure and Local Provider
* `regex` allow to query using regular expressions
* `iRegex` allow to query using case insensitive regular expressions
=> Add regex and iRegex filters to Azure and Local Provider

common/changes/@boostercloud/framework-core/disable_subscriptions_2023-05-27-22-05.json, common/config/rush/pnpm-lock.yaml, packages/framework-provider-aws-infrastructure/src/infrastructure/params.ts, packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/application-stack.ts, packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/graphql-stack.ts, packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/permissions.ts, packages/framework-provider-aws-infrastructure/src/test-helper/aws-test-helper.ts, packages/framework-provider-aws-infrastructure/test/infrastructure/stacks/permissions.test.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/helper/function-zip.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/synth/application-synth.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/synth/terraform-containers.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/synth/terraform-function-app.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/synth/terraform-outputs.ts, packages/framework-provider-local/src/index.ts, packages/framework-provider-local/src/library/read-model-adapter.ts, packages/framework-provider-local/test/library/read-model-adapter.test.ts, packages/framework-types/src/config.ts, website/docs/06_graphql.md
Add config parameter to disable subscriptions artifacts to be created
=> Disable subscriptions

common/changes/@boostercloud/framework-core/add_last_update_to_read_models_2023-04-19-09-38.json, common/config/rush/pnpm-lock.yaml, packages/framework-core/src/services/read-model-store.ts, packages/framework-core/test/services/read-model-store.test.ts, packages/framework-types/src/concepts/read-model.ts
Add last update and last projected entity to read models
=> Add last update and last projected entity to read models

.github/dependabot.yml
=> Enable dependabot.yml

.github/dependabot.yml, .github/workflows/codeql-analysis.yml
Also enabled automatic github action dependencies updates via dependabot
=> Upgrade CodeQL analyzer

website/sidebars.js
Add link to doc which is missing from website
=> Add missing link to website sidebar

website/proposals/0002-project-target/index.mdx, website/proposals/0003-principles-of-design/index.mdx, website/proposals/0004-semantic-versioning/index.mdx, website/proposals/0005-agent-codebase/index.mdx, website/proposals/0006-remote-imports/index.mdx
=> Docs: New BEEPs

website/docusaurus.config.js, website/src/components/Utterance.tsx, website/src/custom.css, website/src/hooks/useUtterance.tsx, website/src/theme/BlogPostPaginator/index.js
=> docs: Add comments for proposal section

.vscode/settings.json, common/changes/@boostercloud/framework-core/chore-upgrade-ts5_2024-01-30-09-03.json, common/config/rush/pnpm-lock.yaml, packages/application-tester/package.json, packages/cli/package.json, packages/cli/src/templates/project/package-json.ts, packages/cli/test/fixtures/mock_project/package.json, packages/framework-common-helpers/package.json, packages/framework-common-helpers/src/instances.ts, packages/framework-core/.mocharc.yml, packages/framework-core/package.json, packages/framework-core/src/decorators/notification.ts, packages/framework-core/src/decorators/read-model.ts, packages/framework-core/src/decorators/sequenced-by.ts, packages/framework-integration-tests/package.json, packages/framework-provider-aws-infrastructure/package.json, packages/framework-provider-aws/package.json, packages/framework-provider-azure-infrastructure/package.json, packages/framework-provider-azure/package.json, packages/framework-provider-local-infrastructure/package.json, packages/framework-provider-local/package.json, packages/framework-types/package.json, packages/metadata-booster/package.json, packages/metadata-booster/src/index.ts, packages/metadata-booster/src/metadata-extractors.ts, packages/metadata-booster/src/statement-creators.ts, tools/eslint-config/package.json, website/docs/10_going-deeper/data-migrations.md, website/package-lock.json, website/package.json
This pull request introduces changes to upgrade the project to TypeScript 5.1.6. The upgrade involves several modifications across various packages and configurations within the project, ensuring compatibility and leveraging new features and improvements brought by TypeScript 5.1.6.
- Upgraded TypeScript version to 5.1.6 across all packages.
- Updated dependencies in various `package.json` files to align with the new TypeScript version.
- Modified the `.mocharc.yml` configuration for Mocha to include `ts-patch/compiler`.
- Adjusted TypeScript related settings in `settings.json` for VSCode.
- Refactored various TypeScript files to comply with new TypeScript version standards and practices.
- Updated `pnpm-lock.yaml` to reflect the new versions of TypeScript and other dependencies.
- …
=> chore: Upgrade to TypeScript 5.1.6

README.md
Fixes "Integration tests" badge
Fixed path to GitHub actions workflow since workflow file name changed
=> fix(docs): Fix readme file integration test badge

common/changes/@boostercloud/framework-core/fix_effect_peer_deps_2024-04-03-17-06.json, common/config/rush/pnpm-lock.yaml, packages/framework-core/package.json, packages/framework-integration-tests/package.json, packages/framework-types/package.json
=> fix: Issues with @effect/printer peer deps

website/docusaurus.config.js
=> feat(docs): update twitter account username

common/changes/@boostercloud/framework-core/enhance_batches_2024-12-26-21-20.json, common/config/rush/pnpm-lock.yaml, packages/framework-provider-azure/src/library/events-store-adapter.ts, packages/framework-provider-azure/test/library/events-store-adapter.test.ts, packages/framework-types/src/config.ts, packages/framework-types/src/provider/azure-configuration.ts, website/docs/10_going-deeper/event-batches.mdx, website/sidebars.js
PR #1436 added the ability to store events in batches. However, there are times when one might want to store events individually due to cost or performance reasons. This PR adds the ability to enable or disable batching events via configuration. It also adds more options for the batch inserts, such as setting the size of the chunks.
* Added the `azureConfiguration` property to the `BoosterConfig` object to set options for batch storage of events.
* Split the `storeEvents`method into two to handle batch and non-batch scenarios.
* Updated unit tests.
* Updated documentation.
=> Enhance storing events in batches in Azure provider

common/changes/@boostercloud/framework-core/enhance_sensors_2025-04-17-19-52.json, common/config/rush/pnpm-lock.yaml, packages/framework-common-helpers/src/http-service.ts, packages/framework-core/src/sensor/health/booster-health-service.ts, packages/framework-core/src/sensor/health/health-indicators/rockets-health-indicator.ts, packages/framework-core/test/sensor/health/booster-health-service.test.ts, packages/framework-core/test/sensor/health/rockets-health-indicator.test.ts, packages/framework-integration-tests/integration/provider-unaware/end-to-end/health.integration.ts, packages/framework-provider-aws/src/setup.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/application-builder.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/azure-stack.ts, packages/framework-provider-azure/src/constants.ts, packages/framework-provider-azure/src/index.ts, packages/framework-provider-azure/src/library/api-adapter.ts, packages/framework-provider-azure/src/library/health-adapter.ts, packages/framework-provider-local/src/index.ts, packages/framework-provider-local/src/library/api-adapter.ts, packages/framework-provider-local/src/library/health-adapter.ts, packages/framework-types/src/provider.ts, website/docs/10_going-deeper/health/sensor-health.md
This PR enhances Booster's health monitoring capabilities by introducing individual rocket health checks and improving the overall health status reporting. These changes make it easier for users to monitor the health of specific rockets and understand the overall system status through standardized HTTP response codes.
* Added support for checking individual rocket health status via `/sensor/health/rockets/rocket-name`
* Introduced standardized HTTP status codes (200/503) to reflect system health
* Improved rocket health status reporting with clearer states (UP, DOWN, PARTIALLY_UP, UNKNOWN)
* Enhanced local provider behavior documentation for rocket health checks
* Standardized rocket naming convention based on package names
* Updated health response handling to consider UNKNOWN rocket …
=> Enhancements to health sensors functionality
