packages/cli/src/commands/new/project.ts, packages/cli/src/services/provider-service.ts
If this is not the case, the deploy fails in the middle of the deploy process, while we could save some time of the user if we check it beforehand. This PR addresses this issue.
=> Ensure that the project name is properly formatted

docs/documentation/09-rest-api.md
A [user pointed out](https://spectrum.chat/boostercloud/general/api-endpoint-empty-response~06306d66-18a5-434f-9643-e1150d7494c2) that they were having issues with the read models endpoint. This is because the docs had a typo and pointed to a wrong endpoint.
=> Fix typo on read models

docs/documentation/08-deployment.md
A user was confused trying to install the AWS CLI, which is not actually required for normal operations
=> Make it clearer that the AWS CLI is optional

packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/application-stack.ts
This fixes an error preventing command handlers from fetching the current state of an entity, as discussed [in this Spectrum thread](https://spectrum.chat/boostercloud/general/how-to-fetchentities~3b33be68-5cc2-411c-a30a-530638ebbcd6).
=> Fix: Added permissions to access DynamoDB tables to the command handler lambda

packages/cli/src/commands/new/read-model.ts, packages/cli/src/services/generator/target/parsing.ts, packages/cli/src/services/generator/target/types.ts, packages/cli/src/templates/index.ts, packages/cli/src/templates/read-model.ts
This PR adds the command 
```
new:readmodel <name> --fields ... --projects entityName:entityId
```
The user can specify many entities within `--projects` like with fields.
=> fix: Generate read-models from CLI

.vscode/launch.json, packages/framework-core/src/booster.ts, packages/framework-integration-tests/src/config/production.ts, packages/framework-provider-aws-infrastructure/src/infrastructure/params.ts, packages/framework-provider-aws-infrastructure/test/infrastructure/stacks/application-stack.test.ts, packages/framework-types/src/config.ts, yarn.lock
To allow the user to set environment variables to be set in the lambdas on deploy time. This is useful to be able to randomize the application name of the example app we're using in the integration tests, but I can see this becoming handier also for setting other configurations depending on the environment on deploy time.
=> Added a new `env` key in `BoosterConfig` 

packages/framework-core/src/decorators/command.ts, packages/framework-core/src/decorators/entity.ts, packages/framework-core/src/decorators/read-model.ts
I got to a situation where I had to rename the file of a read model, but not the class.
When performing a `boost deploy` an interesting thing happened:
```
Read model XXXXX is already registered.
```
What was happening underneath is that the TS compiler was compiling the new file, but the old one was still in the output file folder (`dist`).
Given that Booster imports all the files, it was importing both the old one and the new one. I thought about forcing a clean build on deploy, but that would be too slow for many cases. Added a better hint to the error message.
=> fix: Add better hints to concept errors

packages/framework-core/package.json, packages/framework-core/src/booster-graphql-dispatcher.ts, packages/framework-core/src/booster-subscribers-notifier.ts, packages/framework-core/test/booster-graphql-dispatcher.test.ts, packages/framework-integration-tests/src/config/development.ts, packages/framework-integration-tests/src/config/local.ts, packages/framework-integration-tests/src/deploy.ts, scripts/deploy-example-project-to-aws.js, yarn.lock
Hotfix to fix the regression bug introduced in the latest release that even successful GraphQL executions returned an erroneous result with an empty array of errors
=> Hotfix: Successful GraphQL executions always return an array of empty errors

packages/cli/src/common/script.ts, packages/cli/test/services/script-service.test.ts, packages/framework-integration-tests/integration/aws/auth.integration.ts, packages/framework-integration-tests/integration/aws/commands-api.integration.ts, packages/framework-integration-tests/integration/aws/utils.ts, packages/framework-integration-tests/src/commands/create-product.ts, packages/framework-integration-tests/src/common/money.ts, packages/framework-integration-tests/src/deploy.ts, packages/framework-integration-tests/src/entities/product.ts, packages/framework-integration-tests/src/events/product-created.ts, packages/framework-integration-tests/src/read-models/product-read-model.ts, packages/framework-integration-tests/src/read-models/product-updates-read-model.ts, packages/framework-provider-aws/test/library/read-model-adapter.test.ts, yarn.lock
In this PR we're adding several tests for Booster's authentication API and authorization via GraphQL!
Added integration tests for the following use cases:
* an internet rando
* someone with a user account
* someone with an admin account
Here you have a glorious screenshot of the tests passing in my computer:
* The CLI now prints the whole error stack instead of just the message. I did this because finding the error without the stack was a nighmare.
* This PR also adds a few utility functions to the integration test suite for dealing with AWS stuff
* Added a new task to check subscriptions authentication for the three profiles (BOOST-591)
=> Auth integration tests

packages/cli/src/commands/new/project.ts, packages/cli/src/common/provider.ts
The local provider is still not finished and if you choose it, you will get errors. So I removed it until it is properly working
Remove the Provider.LOCAL option from the enum.
Also added information about which are the default values if you don't write anything in each question the command asks you.
=> Remove the "local provider" option from "boost new:project"

packages/cli/src/commands/new/project.ts, packages/cli/src/common/provider.ts, packages/framework-provider-azure/package.json
- Remove Azure from providers in CLI as it's not ready
- Remove velocity dev dependency
Follow up from https://github.com/theam/booster/pull/86#discussion_r426920179
=> [BOOST-639] Remove Azure from CLI as it's not ready 

packages/framework-provider-aws-infrastructure/src/infrastructure/index.ts
This PR aims to solve this issue #65 
We were using `fromDeploy: true` as a parameter to the CDK `destroy` function. As a result, the word `deployed` was shown right after destroying the stack. I just removed that optional parameter because the [destroy request doesn't come from a deploy](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/cdk-toolkit.ts#L612). Now the word [`destroyed`](https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/cdk-toolkit.ts#L247) is shown.
Closes #65
=> Fix-#65 wrong message when deleting stack with nuke

packages/cli/package.json, packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/application-stack.ts
Just rename those names so that they are more accurate and easy to understand
Mainly `baseRESTURL` to `httpURL`
I'm still working in the documentation for this (which is including the the GraphQL API documentation)
=> Rename the "Outputs" names

packages/framework-provider-aws-infrastructure/package.json, packages/framework-provider-aws-infrastructure/src/infrastructure/index.ts, packages/framework-provider-aws-infrastructure/src/infrastructure/s3utils.ts, yarn.lock
The Nuke operation is not deleting the toolkit stack. This is an issue because these stacks contain an s3 bucket and there is a limit to the number of buckets an account can have. This PR is to ensure that the toolkit stack is removed. To enable that it has been necessary to use the aws-sdk, as the aws-cdk has no knowledge of this stack. There is a previous operation to empty the s3 buckets of the toolkit stack, so that the delete stack operation doesn't fail. 
<Changes made>
The Nuke operation now has an extra step to empty the s3 toolkit bucket and then delete the toolkit stack
There are no tests (unit or integration included in this PR) I'm opening it now so that it can be reviewed and, if it is approved and necessary, merge it into master, so that the …
=> fix(integration): Nuke destroys toolkit stack

docs/examples/cart-service/part-1-build-and-deploy.md
A fix for an example.
I would say that the `newItems` method never includes new SKUs to the list of items. I just came up with this version and now I see new items in my readModel. 
```
{
"data": {
"CartReadModel": {
"id": "demo",
"items": [
{
"sku": "ABC_02",
"quantity": 2
},
{
"sku": "ABC_01",
"quantity": 10
},
{
"sku": "ABC_03",
"quantity": 8
}
]
}
}
}
```
Let me know if it makes sense.
=> Docs: Update part-1-build-and-deploy.md

packages/framework-integration-tests/integration/aws/auth.integration.ts, packages/framework-integration-tests/integration/aws/commands-api.integration.ts
For integration tests, the stack is created and then deleted. The first requests may take longer due to the warm-up time.
- Increase waits in the first test of the authentication and commands-api integration tests suite
=> [INTEGRATION TEST] increase sleep times to allow infrastructure to warm up

CONTRIBUTING.md
Update CONTRIBUTING to explain how to make the "integraiton tests" check go "green" and be able to merge the PR
=> Update CONTRIBUTING with how to run integration tests in PRs

packages/framework-core/src/booster-event-dispatcher.ts, packages/framework-core/src/booster-read-model-dispatcher.ts, packages/framework-core/src/booster-register-handler.ts, packages/framework-core/src/booster-subscribers-notifier.ts, packages/framework-core/src/services/event-store.ts, packages/framework-core/test/booster-event-dispatcher.test.ts, packages/framework-core/test/booster-read-model-dispatcher.test.ts, packages/framework-core/test/booster-register-handler.test.ts, packages/framework-core/test/services/event-store.test.ts, packages/framework-integration-tests/integration/aws/commands-api.integration.ts, packages/framework-provider-aws-infrastructure/package.json, packages/framework-provider-aws-infrastructure/src/infrastructure/index.ts, packages/framework-provider-aws-infrastructure/src/infrastructure/params.ts, packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/application-stack.ts, packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/events-stack.ts, packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/permissions.ts, packages/framework-provider-aws-infrastructure/test/infrastructure/stacks/application-stack.test.ts, packages/framework-provider-aws-infrastructure/test/infrastructure/stacks/permissions.test.ts, packages/framework-provider-aws/src/index.ts, packages/framework-provider-aws/src/library/events-adapter.ts, packages/framework-provider-aws/test/library/events-adapter.test.ts, packages/framework-provider-local/src/index.ts, packages/framework-provider-local/src/library/events-adapter.ts, packages/framework-types/src/config.ts, packages/framework-types/src/provider.ts, packages/framework-types/src/searcher.ts, packages/framework-types/test/config.test.ts
We were using Kinesis to guarantee the order of the events in the event store, but Kinesis price schema is not really "serverless" because it is billed by shards/month. This has two main drawbacks:
* It introduces a minimal fixed monthly price that made some early adopters reject trying the framework; Bad for beginners.
* It could easily become quite expensive or limit the application throughput for big applications; Bad for pro users too.
In this PR we replace Kinesis by DynamoDB Streams, which offer a nearly identical API with similar guarantees, and has a pure pay-per-use schema that also scales automatically.
_**Note:** This PR is a refurbished version of PR #85, which was already reviewed and approved. For this version review, focus on [the latest …
=> BOOST-693 Replace Kinesis by DynamoDB Streams

packages/framework-core/src/booster-command-dispatcher.ts, packages/framework-core/src/booster-register-handler.ts, packages/framework-core/test/booster-command-dispatcher.test.ts, packages/framework-core/test/booster-register-handler.test.ts, packages/framework-core/test/decorators/command.test.ts, packages/framework-integration-tests/src/commands/change-cart-item.ts, packages/framework-integration-tests/src/commands/confirm-payment.ts, packages/framework-integration-tests/src/commands/create-product.ts, packages/framework-integration-tests/src/commands/delete-product.ts, packages/framework-integration-tests/src/commands/update-product.ts, packages/framework-integration-tests/src/commands/update-shipping-address.ts, packages/framework-types/src/concepts/command.ts, yarn.lock
This PR fixes a bug that happened always when the command handler does an asynchronous operation (uses `await` for example). Booster called the command handler without `await`, so the provider lambda finished before giving a chance to the command handler to finish.
* The return type of command handlers is now `Promise<void>` as it should have been
* Added the corresponding await
* Do not handle events after the command handler finished if there were no events registered
* Added new tests for these new cases.
=> Fix: Await for command handlers to finish

packages/framework-integration-tests/.eslintignore, packages/framework-integration-tests/integration/cli/cli.command.integration.ts, packages/framework-integration-tests/integration/cli/cli.entity.integration.ts, packages/framework-integration-tests/integration/cli/setup.ts, packages/framework-integration-tests/integration/fixtures/commands/ChangeCart.ts, packages/framework-integration-tests/integration/fixtures/commands/ChangeCartWithFields.ts
Create integration tests to check that the files generated are what it is expected. Also, verify that the code compiles.
- Create integration tests for commands generation
- Check command generation error
- Little refactor to entity cli integration tests
=> [BOOST-571] adds command generation integration tests

.github/dependabot.yml
Dependabot was bumping major versions with breaking changes, and tests were failing. We should only upgrade major dependency versions on purpose.
I also restricted the PRs to master to avoid duplicate PRs in mirrored repositories
=> Updated Dependabot config to apply security updates exclusively

docs/README.md
In the rewriting of the docs we will be opening several PRs, one per section, so we end up with the documentation in a single markdown file.
Add a section for Installing the Booster CLI so a user can later follow the 10 minutes tutorial
=> Add a section for installing the Booster CLI

.markdownlintrc
We are using a linter that can be configured via config file, I added that config file so we can fine-tune our markdown linting.
I linked the rules description in the config file to have them handy
=> docs: add markdownlintrc file so we can configure the linting of the docs

packages/framework-integration-tests/integration/end-to-end/setup.ts, packages/framework-integration-tests/integration/providers/aws/setup.ts, packages/framework-integration-tests/package.json
Adds AWS configuration to end-to-end tests and update scripts to include the environment variable needed for AWS `AWS_SDK_LOAD_CONFIG=true`.
Added the flag `FULL_INTEGRATION_TEST`, which makes the AWS setup config to not nuke the application stack, allowing the end-to-end tests to reuse it and nuke it when it finishes, reducing the amount of times we have to deploy/nuke the test application stack.
- Update integration scripts in `package.json`
- Add AWS setup in end-to-end `setup.ts`
=> BOOST-728: fix end to end tests

packages/framework-integration-tests/integration/cli/cli.command.integration.ts, packages/framework-integration-tests/integration/cli/cli.type.integration.ts, packages/framework-integration-tests/integration/cli/setup.ts, packages/framework-integration-tests/integration/fixtures/common/CartItem.ts, packages/framework-integration-tests/integration/fixtures/common/CartItemWithFields.ts
Create integration tests to check that the files generated are what it is expected.
- Creates integration tests for types generation.
- Rename some variables in the commands generation tests.
=> [BOOST-575] adds type generation integration tests

.vscode/launch.json, lerna.json, package.json, packages/cli/src/commands/new/project.ts, packages/cli/src/common/provider.ts, packages/framework-provider-kubernetes-infrastructure/.eslintignore, packages/framework-provider-kubernetes-infrastructure/.mocharc.yml, packages/framework-provider-kubernetes-infrastructure/package.json, packages/framework-provider-kubernetes-infrastructure/src/index.ts, packages/framework-provider-kubernetes-infrastructure/tsconfig.eslint.json, packages/framework-provider-kubernetes-infrastructure/tsconfig.json, packages/framework-provider-kubernetes/.eslintignore, packages/framework-provider-kubernetes/.mocharc.yml, packages/framework-provider-kubernetes/package.json, packages/framework-provider-kubernetes/src/index.ts, packages/framework-provider-kubernetes/tsconfig.eslint.json, packages/framework-provider-kubernetes/tsconfig.json, yarn.lock
In this PR we are adding the foundations for the Kubernetes provider. The new provider is also added to the CLI because this feature is going to be implemented in a feature branch separated from master (check the base branch in this PR)
- Added the new packages `framework-provider-kubernetes` and `framework-provider-kubernetes-infrastructure`
- Added all the minimum configuration stuff inside of each package
- Added the new provider to the create-project command in the CLI.
=> [BOOST-710] added kubernetes provider skeleton

.github/dependabot.yml
We are receiving a handful lot of PRs every day due to the frequency we have set for Dependabot to check. I suggest that we set that check to be run once a week.
- Dependabot config updated
=> Update dependabot schedule interval to 1 week

packages/framework-integration-tests/integration/cli/cli.project.integration.ts, packages/framework-integration-tests/integration/cli/setup.ts, packages/framework-integration-tests/integration/fixtures/cart-demo/.eslintignore, packages/framework-integration-tests/integration/fixtures/cart-demo/.eslintrc.js, packages/framework-integration-tests/integration/fixtures/cart-demo/.gitignore, packages/framework-integration-tests/integration/fixtures/cart-demo/.prettierrc.yaml, packages/framework-integration-tests/integration/fixtures/cart-demo/package.json, packages/framework-integration-tests/integration/fixtures/cart-demo/src/config/config.ts, packages/framework-integration-tests/integration/fixtures/cart-demo/src/index.ts, packages/framework-integration-tests/integration/fixtures/cart-demo/tsconfig.eslint.json, packages/framework-integration-tests/integration/fixtures/cart-demo/tsconfig.json, packages/framework-integration-tests/integration/helper/fileHelper.ts
Add tests for project generators and checking that the generating files can be compiled.
* CLI integration tests are added
I've been struggling with providing stdin inputs for the CLI prompts. Since these are integration tests, I didn't want to mock the prompt operation (provided by the library called [inquirer](https://www.npmjs.com/package/inquirer)), so I finally came up with an approach that is able to write in the writable stdin. I had to use an interval to send the answers, though. I've not found any other approach that worked fine so far. I found several articles to mock the prompt operation ([this is a good one by the way](https://glebbahmutov.com/blog/unit-testing-cli-programs/)), but I was not able to find a better approach for our use case. Feel free to discuss it!
I'll open an …
=> Project generators integration tests

packages/framework-provider-aws-infrastructure/src/infrastructure/s3utils.ts, packages/framework-provider-aws-infrastructure/test/infrastructure/s3utils.test.ts
Handles the error returned when there isn't any static site bucket to be deleted
- Create new function in `s3utils.ts` to check whether there is a bucket available
- Adds new logic to avoid deleting an inexistent bucket
=> Fix: error when static site bucket not found

packages/cli/src/commands/new/project.ts, packages/framework-integration-tests/integration/cli/cli.project.integration.ts
Update the flag for homepage when creating a new project with CLI.
Changed to `-H` since it's still related to the word. 
Unskipped the test related to short flags since it's working now.
If there is any other consensus on what letter to use, feel free to add it as a suggestion since the changes required for this to work are small enough
- Update short flag to `-H`
- Unskip integration test
- [] Updated documentation accordingly
=> BOOST-754: change flag for homepage and unskip the short flag integration tests

docs/README.md, package.json
In addition to the toc itself, this PR adds a development dependency and a script for updating the table of content just by running `npm run update-documentation-toc` in the root directory. That is one step behind automatizing this flow with a GitHub action.
There were 2 subsections with a wrong indentation level, I fixed that (the TOC make the error pretty clear :P )
=> Add a table of content at the beginning of the docs

docs/README.md
When creating your first project in Booster, it's common to get confused about where to put your role classes. Booster doesn't require to put them in any specific place, but it's a good idea to give a suggestion.
=> Added a suggestion to place role classes

packages/framework-integration-tests/integration/providers/aws/setup.ts, packages/framework-integration-tests/integration/providers/aws/subscriptions.integration.ts
After a whole day of chasing the random errors we were getting in integration tests, it turned out that we needed to wait for some time after the deployment of the AWS stack. 
This explains why the integration tests always worked in stacks that had been already deployed before, and not in new stacks that had been deployed right before the tests start.
I also took the opportunity to do some other reactors to increase the reliability of tests
- ~[ ] Updated documentation accordingly~
=> Wait after integration tests deployment and before tests begin

docs/README.md
This change is because this discussion https://github.com/boostercloud/booster/pull/226#discussion_r450902651 
It would be great if we, somehow, run a static analysis of the events' code to determine if their entityID methods are pure or not.
=> Rephrase the event's introduction to avoid random values in the entityID method

.markdownlintrc
Most editors wrap lines at the desired column and this rule is making code review harder
=> Disable line length for markdown linter

packages/framework-core/test/services/graphql/graphql-type-informer.test.ts
Create Type Informer Generator tests
- Add tests for Type Informer generator
=> Graphql type informer generator tests

packages/cli/src/common/script.ts, packages/cli/test/commands/deploy.test.ts, packages/cli/test/commands/nuke.test.ts, packages/cli/test/services/script-service.test.ts, packages/framework-integration-tests/integration/cli/cli.project.integration.ts
When a compilation error happens, even if the error is logged the return value is actually 0. This is problematic when integrating booster applications with CD tools like Circle CI. As described in the ticket https://agilemonkeys.atlassian.net/browse/BOOST-870 the deploy step was marked successful because of the return value.
Throw an exception instead of just logging the error.
Also ran `lerna run integration/cli` to run the integration tests for the CLI package where all the changes happen.
=> [BOOST-870] Return value different from 0 for  compilation error

docs/README.md, packages/framework-core/src/booster-auth.ts, packages/framework-core/test/booster-auth.test.ts, packages/framework-core/test/booster-read-model-dispatcher.test.ts, packages/framework-core/test/booster-register-handler.test.ts, packages/framework-core/test/services/graphql/graphql-generator.test.ts, packages/framework-integration-tests/integration/providers/aws/auth.integration.ts, packages/framework-integration-tests/integration/providers/aws/event-handlers.integration.ts, packages/framework-integration-tests/integration/providers/aws/utils.ts, packages/framework-integration-tests/integration/providers/local/auth.integration.ts, packages/framework-integration-tests/integration/providers/local/commands.integration.ts, packages/framework-integration-tests/integration/providers/local/utils.ts, packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/api-stack-velocity-templates.ts, packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/auth-stack.ts, packages/framework-provider-aws-infrastructure/test/infrastructure/stacks/api-stack-velocity-templates.test.ts, packages/framework-provider-aws/src/library/user-envelopes.ts, packages/framework-provider-aws/test/library/auth-adapter.test.ts, packages/framework-provider-aws/test/library/graphql-adapter.test.ts, packages/framework-provider-aws/test/library/user-envelopes.ts, packages/framework-provider-local-infrastructure/test/controllers/auth.test.ts, packages/framework-provider-local/src/library/auth-adapter.ts, packages/framework-provider-local/src/library/graphql-adapter.ts, packages/framework-provider-local/src/services/user-registry.ts, packages/framework-provider-local/test/library/graphql-adapter.test.ts, packages/framework-provider-local/test/services/user-registry.test.ts, packages/framework-types/src/envelope.ts
Allow only one role per user.
After some conversations, we realized allowing a user to have multiple roles can be conflicting. Since roles have their one attributes, applying multiple roles to a single user with conflicting attributes values is misleading.
Also ran integration tests.
=> [BOOST-925] Allow only single Role per User

docs/README.md
Changes the subscription docs so users know that they should specify the `Sec-WebSocket-Protocol` header to `graphql-ws` on their clients. Otherwise, you will receive this error:
`➜  ~ wscat -c wss://be2n7ubdoi.execute-api.eu-west-1.amazonaws.com/test/
error: Server sent a subprotocol but none was requested`
=> Add graphqlws subprotocol to the subscription part of the documentation

docs/README.md, packages/framework-core/package.json, packages/framework-core/src/booster-auth.ts, packages/framework-core/test/booster-auth.test.ts, packages/framework-core/test/booster-read-model-dispatcher.test.ts, packages/framework-core/test/booster-register-handler.test.ts, packages/framework-integration-tests/integration/end-to-end/cart.integration.ts, packages/framework-integration-tests/integration/providers/aws/auth.integration.ts, packages/framework-integration-tests/integration/providers/aws/event-handlers.integration.ts, packages/framework-integration-tests/integration/providers/aws/utils.ts, packages/framework-integration-tests/integration/providers/local/commands.integration.ts, packages/framework-integration-tests/src/commands/CreateProduct.ts, packages/framework-integration-tests/src/read-models/product-read-model.ts, packages/framework-integration-tests/src/roles.ts, packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/api-stack-velocity-templates.ts, packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/auth-stack.ts, packages/framework-provider-aws-infrastructure/test/infrastructure/stacks/api-stack-velocity-templates.test.ts, packages/framework-provider-aws-infrastructure/test/infrastructure/stacks/application-stack.test.ts, packages/framework-provider-aws/src/library/user-envelopes.ts, packages/framework-provider-aws/test/library/auth-adapter.test.ts, packages/framework-provider-aws/test/library/graphql-adapter.test.ts, packages/framework-provider-local/src/library/auth-adapter.ts, packages/framework-provider-local/src/library/graphql-adapter.ts, packages/framework-provider-local/src/services/user-registry.ts, packages/framework-provider-local/test/library/graphql-adapter.test.ts, packages/framework-provider-local/test/services/user-registry.test.ts, packages/framework-types/src/concepts/role.ts, packages/framework-types/src/envelope.ts, packages/framework-types/test/config.test.ts
- Add phone authentication
- Add authentication wrapper in Role Decorator
- Change boolean allowSelfSignUp with array SignUpOptions with values email and/or phone
Added phone authentication properly working with AWS provider (Cognito)
=> [BOOST-707] Add phone authentication

packages/cli/src/commands/new/command.ts, packages/cli/src/commands/new/entity.ts, packages/cli/src/commands/new/event-handler.ts, packages/cli/src/commands/new/event.ts, packages/cli/src/commands/new/project.ts, packages/cli/src/commands/new/read-model.ts, packages/cli/src/commands/new/type.ts
This PR fix how we were returning error messages, so instead of throwing the whole Error object we simply return the string error message.
=> fix(cli) error messages on empty artifact names

packages/framework-integration-tests/integration/providers/aws/utils.ts
Since the CI/CD job is failing due to a timeout, in this PR we've increased the timeout limit of `waitForIt` to 5min.
=> Increase timeout of waitForIt to 5min

docs/README.md, packages/cli/src/commands/new/project.ts, packages/cli/src/services/project-initializer.ts, packages/cli/test/commands/new.test.ts
Right now, the `boost new:project <project-name>` was missing generating two folders in the `src` directory of our project: event-handlers and read-models.
- Add `event-handlers` and `read-models` folders to the project initializer
- Created a test to check the content of our project (directory-based) by checking the project's root and src directories
**Related issue:** https://github.com/boostercloud/booster/issues/289
As usual, let me know if you think I'm missing something. Thanks!
=> Issue #289 - Add missing folders to project generator 

docs/README.md, packages/cli/src/commands/new/read-model.ts, packages/cli/src/templates/read-model.ts, packages/cli/test/commands/new.test.ts, packages/framework-core/src/decorators/projection.ts, packages/framework-core/src/services/read-model-store.ts, packages/framework-core/test/decorators/read-model.test.ts, packages/framework-core/test/services/read-model-store.test.ts, packages/framework-integration-tests/integration/end-to-end/cart.integration.ts, packages/framework-integration-tests/integration/fixtures/read-models/CartReadModel.ts, packages/framework-integration-tests/integration/fixtures/read-models/CartWithFieldsReadModel.ts, packages/framework-integration-tests/integration/fixtures/read-models/CartWithProjectionReadModel.ts, packages/framework-integration-tests/src/read-models/cart-read-model.ts, packages/framework-integration-tests/src/read-models/product-read-model.ts, packages/framework-integration-tests/src/read-models/product-updates-read-model.ts, packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/permissions.ts, packages/framework-provider-aws-infrastructure/test/infrastructure/stacks/permissions.test.ts, packages/framework-provider-aws/src/index.ts, packages/framework-provider-aws/src/library/read-model-adapter.ts, packages/framework-provider-aws/test/library/read-model-adapter.test.ts, packages/framework-provider-azure/src/index.ts, packages/framework-provider-kubernetes/src/index.ts, packages/framework-provider-local/src/index.ts, packages/framework-provider-local/src/library/graphql-adapter.ts, packages/framework-provider-local/test/library/graphql-adapter.test.ts, packages/framework-types/src/concepts/projection-metadata.ts, packages/framework-types/src/provider.ts
This reverts commit a17b4d46a2c60204f5391ff6d4804e74e1fb9564, reversing
changes made to e53db551811da3acfcf25b07122a45ba8a1290ac.
It looks like the integration tests had some errors, I'm reverting and opening a new PR. It was a mix of lint issues and this `Error: Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves` (??). I'll check it
This reverts: https://github.com/boostercloud/booster/pull/404
=> Revert "Delete read model"

docs/README.md, packages/cli/src/commands/new/project.ts, packages/cli/src/services/project-initializer.ts, packages/cli/test/commands/new.test.ts
Now, when running `boost new:project <my-project> --default`, booster will create the project with all default parameters, without asking the user.
- Added a `--default` (or `-d`) flag
- Stopped the "CLI prompt flow" and returned the default parameters from `parseConfig` function when that flag is present
- Wrote tests and refactor common cases from both ones
Fixes #115
=> I115 - Allow generating a new project with default parameters

docs/README.md, packages/cli/src/commands/new/read-model.ts, packages/cli/src/templates/read-model.ts, packages/cli/test/commands/new.test.ts, packages/framework-core/src/decorators/projection.ts, packages/framework-core/src/services/read-model-store.ts, packages/framework-core/test/decorators/read-model.test.ts, packages/framework-core/test/services/read-model-store.test.ts, packages/framework-integration-tests/integration/end-to-end/cart.integration.ts, packages/framework-integration-tests/integration/fixtures/read-models/CartReadModel.ts, packages/framework-integration-tests/integration/fixtures/read-models/CartWithFieldsReadModel.ts, packages/framework-integration-tests/integration/fixtures/read-models/CartWithProjectionReadModel.ts, packages/framework-integration-tests/src/read-models/cart-read-model.ts, packages/framework-integration-tests/src/read-models/product-read-model.ts, packages/framework-integration-tests/src/read-models/product-updates-read-model.ts, packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/permissions.ts, packages/framework-provider-aws-infrastructure/test/infrastructure/stacks/permissions.test.ts, packages/framework-provider-aws/src/index.ts, packages/framework-provider-aws/src/library/read-model-adapter.ts, packages/framework-provider-aws/test/library/read-model-adapter.test.ts, packages/framework-provider-azure/src/index.ts, packages/framework-provider-kubernetes/src/index.ts, packages/framework-provider-local/src/index.ts, packages/framework-provider-local/test/library/graphql-adapter.test.ts, packages/framework-types/src/concepts/projection-metadata.ts, packages/framework-types/src/provider.ts
**Note:** This is a copy from https://github.com/boostercloud/booster/pull/404, but fixing CLI integration tests
With this change, a developer will be able to delete their read models by returning the `deleteReadModel` type. Here's an example:
```
@ReadModel
export class UserReadModel {
public constructor(readonly username: string, /* ...(other interesting fields from users)... */) {}
@Projects(User, 'id')
public static projectUser(entity: User, current?: UserReadModel): ProjectionResult<UserReadModel> {
if (isReadModelDeletable()) {
return deleteReadModel // This is a type from ProjectionResult
}
return new UserReadModel(...)
}
private isReadModelDeletable(): boolean {
...
}
```
1. Insert a `deleteReadModel` in the `read-model-store` flow, which ends up calling `read-model-adapter` and …
=> Delete read models when projecting null

packages/framework-core/src/booster-event-dispatcher.ts, packages/framework-core/src/services/read-model-store.ts, packages/framework-core/test/booster-event-dispatcher.test.ts, packages/framework-core/test/decorators/event-handler.test.ts, packages/framework-core/test/services/read-model-store.test.ts, packages/framework-integration-tests/integration/cli/cli.project.integration.ts, packages/framework-integration-tests/integration/helper/fileHelper.ts, packages/framework-types/src/concepts/event-handler.ts
We were calling the "handle" methods of event handlers without an `await`, what means that if the user included an async call in the handler, it won't work. This bug was found by @otoumas 
Added the `await` keyword and a test to ensure it won't happen again
=> Fix missing await in event handler

packages/framework-integration-tests/integration/providers/aws/cors.integration.ts, packages/framework-integration-tests/integration/providers/aws/functionality/auth.integration.ts, packages/framework-integration-tests/integration/providers/aws/functionality/cors.integration.ts, packages/framework-integration-tests/integration/providers/aws/utils.ts, packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/auth-stack.ts
> Notice that this PR was recreated after rebasing PR #388
This PR resolves #387 
The Auth Stack generates the auth API with preflight support (accept OPTIONS requests) for the `auth/sign-up`, `auth/sign-in` ,and `auth/sign-out` endpoints. Also, the corresponding `POST` methods return the `Access-Control-Allow-Origin: *' header.
The integration test verifies the OPTIONS requests for almost all the used HTTP verbs. Regarding the Posts request, there are three tests pending because it is difficult to test the response for 500 errors.
Note that this solves the issue only for the AWS provider. However, I wrote the test suite as a black box one, so we can move it up and run it against all the providers' implementations. At this moment the best would be open tickets for reproducing the solution …
=> Enable CORS in the auth endpoints

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md
When I opened issue for git initialization with CLI `--no-git` flag I saw blank issue and didn't know how to write what I wanted to add. This PR will allow users to add new issue for `bug report` / `documentation bug(improvement)` / `feature request` templates. They can be improved to collect more information from user, or separated for each package `cli feature` or `cli bug` for example.
=> GitHub issue template

packages/cli/src/templates/project/index-ts.ts, packages/framework-integration-tests/integration/fixtures/cart-demo/src/index.ts
CLI integration tests are failing and the new version with the `ScheduledCommands` functionality can't be built. This was happening because the CLI tests were trying to export the new `boosterTriggerScheduledCommand` function from the core, but it didn't exist because it was installing the previous version of Booster `v8.1`. 
This fix removes the export of that function, allowing the CLI tests to use the previous version, once this is merged I'll submit some changes to the `ScheduledCommands`, including the usage of these functions in the tests.
=> fix cli integration tests

packages/cli/src/commands/new/project.ts, packages/cli/src/services/project-initializer.ts, packages/cli/test/commands/new.test.ts
CLI flag to skip dependency installation. According to https://github.com/boostercloud/booster/issues/156#issuecomment-667982702 
There is no documentation about CLI commands
=> feat(cli): implement --skipInstall flag

packages/cli/src/templates/project/index-ts.ts, packages/framework-integration-tests/integration/fixtures/cart-demo/src/index.ts, scripts/check-all-the-things.sh
When `ScheduledCommands` were implemented, we spotted that there was an issue when creating the projects in the CLI tests, because it was trying to export a new booster function from an older version of the project, in which it didn't exist.
Just added the `ScheduledCommands` booster function to the CLI tests.
- ~[ ] Updated documentation accordingly~ Not necessary
It passes all tests, including CLI except the ones that are failing now in master.
=> add scheduled commands func to cli tests

packages/cli/src/commands/deploy.ts, packages/cli/src/commands/nuke.ts, packages/cli/src/commands/start.ts, packages/cli/src/common/environment.ts, packages/cli/src/services/config-service.ts, packages/cli/test/commands/deploy.test.ts, packages/cli/test/commands/nuke.test.ts, packages/cli/test/commands/start.test.ts, packages/cli/test/services/config-service.test.ts, packages/framework-core/src/booster.ts, packages/framework-core/test/booster.test.ts, packages/framework-types/src/booster-app.ts, packages/framework-types/src/config.ts
This is a minor refactor. I noticed some details that the environment management in configuration that made me think that the way we were managing them was a bit fragile:
* We were dealing with system environment variables from the cli scripts
* We had a list of available environments in the config that was only used by the CLI to display them when there were errors. The config is the config for a specific environment, so it doesn't make sense that it has getters and setters for things that are unrelated.
* The tests were rewriting `require`
* Created a new `environment` module with higher-level functions to write and read the current environment
* Moved the `configuredEnvironments` list from `BoosterConfig` to `BoosterApp`
* Fixed (and improved a little) the tests
~~Updated documentation …
=> Reworked the way environments are managed by the CLI

packages/framework-integration-tests/integration/providers/aws/functionality/event-handlers.integration.ts, packages/framework-integration-tests/integration/providers/aws/utils.ts, yarn.lock
Some AWS integration tests were using the `currentUser` in some assertions and, since the internal user envelope contains the userId we'll need to get the one returned by Cognito.
- Added a helper function to get the Cognito UserId
=> fix: fixed aws event handlers integration tests

packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/permissions.ts, packages/framework-provider-aws-infrastructure/test/infrastructure/stacks/permissions.test.ts, packages/framework-types/src/booster-app.ts
This is a quick PR to export the function that allows to search read models from any handler. 
Note: `Booster.readModels` function is still undocumented and under a heavy refactor, expect breaking changes
- ~[ ] Updated documentation accordingly~
=> Export Booster.readModel() method

.github/workflows/publish.yml
Instead of restoring the `yarn.lock` file we stash all the changes performed during the test execution
- Changed publish config file
=> fix: stash changes after integration tests

packages/cli/package-lock.json, packages/framework-core/package-lock.json, packages/framework-core/src/booster-auth.ts, packages/framework-core/src/booster-graphql-dispatcher.ts, packages/framework-core/src/booster-token-verifier.ts, packages/framework-core/src/services/graphql/websocket-protocol/graphql-websocket-protocol.ts, packages/framework-core/test/booster-auth.test.ts, packages/framework-core/test/booster-graphql-dispatcher.test.ts, packages/framework-core/test/booster-token-verifier.test.ts, packages/framework-core/test/services/graphql/websocket-protocol/graphql-websocket-protocol.test.ts, packages/framework-provider-aws-infrastructure/package-lock.json, packages/framework-provider-aws/package-lock.json, packages/framework-provider-local-infrastructure/package-lock.json, packages/framework-provider-local/package-lock.json, yarn.lock
This PR contains an improvement to use the jwks client cache while the graphQL handler lambda is still executing. This change will allow us to avoid creating a jwks client on each token verification and also avoid hitting the key set endpoint producing a rate limit.
I did this change after detect that some tests were locked randomly without any reason, so maybe we've fixed the root case. 
- Created a new class with all the functionality we had in Booster Auth.
- Fixed tests
- Set the cache limit to the max limit of the lambda execution time (AWS only). For now is enough.
We'll need to research a bit more about how different providers use the jwks uris. If the providers invalidates them we should detect that, invalidate our cache and configure a new client.
=> fix: added booster token verifier class

packages/framework-integration-tests/package.json, packages/framework-provider-local/src/library/read-model-adapter.ts, packages/framework-provider-local/src/library/searcher-adapter.ts, packages/framework-provider-local/test/library/read-model-adapter.test.ts, packages/framework-provider-local/test/library/searcher-adapter.test.ts, yarn.lock
Adds the possibility of querying read models in the local provider, for example, by using queries like this:
```graphql
query{
ProductReadModels(description: {operation: not_contains, values: ["hot"]}){
id
...
}
}
```
Created a `searcher-adapter.ts` module that converts Booster GraphQL queries into query operations supported by NeDB.
It's missing the tests, but you can review for now.
=> Local provider - Queries

docs/README.md
Just added a note clarification about that there is not Admin user by default.
One line in the docs README. 
[It ain't much but it's honest work](https://en.meming.world/images/en/thumb/b/be/But_It%27s_Honest_Work.jpg/300px-But_It%27s_Honest_Work.jpg)
=> Add no admin by default note in auth docs

packages/framework-integration-tests/integration/providers/aws/deployment/deployment.integration.ts
When deploying a Booter app that already exists in AWS, it throws an error because a test is expecting a `CREATE_COMPLETED` message from `CloudFromation`. This error is commonly seen after a failed integration test.
The tests expect now either a `CREATE_COMPLETED` or a `UPDATE_COMPLETED` message, which allows updating an existing stack without errors.
=> Fix test failure when stack already exists

CONTRIBUTING.md
Update Contributing documentation to consider branch naming conventions in PRs
I updated CONTRIBUTING.md to include more details related to branch naming conventions
=> docs: include branch naming conventions section

CONTRIBUTING.md, docs/README.md, package.json, packages/framework-core/test/booster-command-dispatcher.test.ts, packages/framework-provider-aws/test/library/subscription-adapter.test.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/utils.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/utils.ts, packages/framework-types/src/concepts/uuid.ts
**Note: This code was already reviewed and approved in #498**
While working on the first spike to switch to npm (#496) I applied several fixes/improvements to a few tests, but that branch was closed. This branch cherry-picked the nice parts that deserve being saved.
> This PR is a rebase of #498. We're switching to npm and the current master is too unstable for integration tests to pass, so we'll try better luck using npm.
* Documented the process to run integration tests in the CONTRIBUTING.md guide.
* Fixed Booster Command Dispatcher unit tests in the `framework-core` package.
* Reviewed subscription adapter unit tests in the `framework-provider-aws` package.
* Fixed a small issue in the azure and kubernetes infrastructure packages related to promise handling.
* Minor change in the way …
=> Remainders and fixes from the previous "yarn to npm" spike

docs/README.md
Postwoman link is deprecated.
<Changes made> 
Change postwoman link for the new one (Hoppscotch link).
=> doc: fix postwoman link

packages/framework-core/src/booster-graphql-dispatcher.ts, packages/framework-core/src/booster-subscribers-notifier.ts, packages/framework-core/src/services/graphql/graphql-generator.ts, packages/framework-core/test/services/graphql/graphql-generator.test.ts
Refactor GraphQLGenerator class to access it in a uniform way. Applying Singleton pattern. Since config: BoosterConfig is declared as static in Booster class, all classes that access config access the same instance of BoosterConfig. Taking that into account, the design has been simplified.
Fixes #541 
- I made this class initialized via a Singleton getInstance() method
- Client classes get the GraphQLGenerator singleton instance to use it
- Update unit tests
- [] Updated documentation accordingly
=> 541 refactor GraphQLGenerator class

.github/workflows/lint.yml, .github/workflows/publish.yml, .github/workflows/tests.yml, .markdownlintrc, CONTRIBUTING.md, README.md, docs/README.md
Github, Git and many other organizations and open-source communities are proposing to rename `master` branch as `main` [for the reasons explained in this document](https://sfconservancy.org/news/2020/jun/23/gitbranchname/) to abandon old terminology that doesn't make sense anymore.
In this PR, I've renamed all references to the `master` branch and replaced them by `main`. Once it's merged, Github has prepared a guide and automations to easily migrate all PRs, so this should be a seamless change: https://github.com/github/renaming
Bonus: I also removed the unused references to `master-mirror`
=> Switch to `main` as the base branch of the project

.github/workflows/publish.yml
I went too far with the search and replace when we switched to using the branch `main` as the production one in #591
=> Fix: Reference error in publish GitHub action script

docs/README.md, packages/cli/src/commands/new/project.ts, packages/cli/src/services/generator.ts, packages/cli/src/services/generator/target/index.ts, packages/cli/src/services/project-checker.ts, packages/cli/src/services/project-initializer.ts, packages/cli/src/services/user-prompt.ts, packages/cli/test/services/generator.test.ts, packages/cli/test/services/project-checker.test.ts, packages/cli/test/services/user-prompt.test.ts, packages/framework-integration-tests/integration/cli/cli.event.integration.ts, packages/framework-integration-tests/integration/cli/cli.readmodel.integration.ts
PR created on behalf of @Fecony and related to this external PR https://github.com/boostercloud/booster/pull/475
Check if project folder or resource already exist before generating new file. It will ask user if he wants to override existing file and continue or stop generating. If user agrees to override it file/project folder is removed. If declines then it will throw error for user to use different resource name. (See Images below) 
Closes https://github.com/boostercloud/booster/issues/305
- Checks if project or file already exist.
- export `projectDir()`
- Adds `checkProjectAlreadyExists()` to check if project already exists in current directory.
- Adds `checkResourceExists()` to check if resource already exists.
- Unit tests for `checkProjectAlreadyExists()` and …
=> PR from Fecony's contribution to ask for removing files

docs/README.md, packages/framework-core/src/booster-read-model-dispatcher.ts, packages/framework-core/src/services/graphql/graphql-generator.ts, packages/framework-core/src/services/pub-sub/read-model-pub-sub.ts, packages/framework-provider-aws-infrastructure/src/infrastructure/stacks/permissions.ts, packages/framework-provider-aws-infrastructure/test/infrastructure/stacks/permissions.test.ts, packages/framework-provider-aws/src/library/searcher-adapter.ts, packages/framework-provider-aws/test/library/searcher-adapter.test.ts, packages/framework-provider-azure/src/library/searcher-adapter.ts, packages/framework-provider-azure/test/library/searcher-adapter.test.ts, packages/framework-provider-local/src/index.ts, packages/framework-provider-local/src/library/read-model-adapter.ts, packages/framework-provider-local/src/library/searcher-adapter.ts, packages/framework-types/src/envelope.ts, packages/framework-types/src/provider.ts, packages/framework-types/src/searcher.ts
This new way of filtering is based on the Amplify one, which is way less limiting than the previous one.
* The core `searcher` function has been changed to the new format. The old filter system is still compatible until we update the rest of the providers.
* The AWS `searcher-adapter` has been modified to translate these new filters to DynamoDB queries.
* Unit tests for AWS `searcher-adapter` has been added to ensure stability across all the different scenarios.
This is working just for retrieving and filtering ReadModels inside commands, events, etc. The GraphQL schema will be changed in a future PR.
=> New GraphQL filters

CONTRIBUTING.md, package.json
Fix markdown-toc markdown file generation. When running `npm run update-tocs` markdown list bullet style was changed, CONTRIBUTING.md file `-` list bullet style was changed to `*` since it is default bullet style.
> CONTRIBUTING.md missing links and not existing links where added/removed after running `npm run update-tocs`
- Fixed bullet list generation
- CONTRIBUTING.md has `-` bullet style. 
- docs/README.md file uses 3 bullet styles for different nesting levels `-`, `*`, `+`
=> Doc: fix markdown-toc markdown generation

packages/rocket-batch-file-process-aws-infrastructure/README.md, packages/rocket-batch-file-process-aws-infrastructure/package.json, packages/rocket-batch-file-process-aws-infrastructure/src/batch-file-processing.ts, packages/rocket-batch-file-process-aws-infrastructure/src/file-splitter-lambda/index.ts, packages/rocket-batch-file-process-aws-infrastructure/src/file-splitter-lambda/package.json, packages/rocket-batch-file-process-aws-infrastructure/src/file-to-line-event-lambda/index.ts, packages/rocket-batch-file-process-aws-infrastructure/src/file-to-line-event-lambda/package.json
This PR extends the current Batch file rocket to the next level of abstraction.
As of now we used to receive a `FileAdded` event in the Event Handler representing the chunked file but we still needed to use the AWS sdk to open the file, split by "," if CSV file and etc.. logic that we can abstract to the rocket.
This PR does that. We receive an event representing a line of the file directly.
Also, add support for jsonl files
New files.
=> Extend Batch file Rocket: row event from event handler + add support for jsonl files

packages/cli/src/commands/new/entity.ts
This is a simple bug fix described in https://github.com/boostercloud/booster/issues/628 where the new:entity cli command flag needed an update.
Changed the flag from p to r.
I could not find anything in the documentation that needed an update as a result of this change.
=> fix(cli): update new:entity command flag

packages/framework-provider-local/package.json
Running the boost start -e <environment> command throws error about missing @types/nedb dependency as pointed out in the Issue https://github.com/boostercloud/booster/issues/623 
One line change to move `@types/nedb` devDependency in local provider to dependencies block.
Nothing to update in the documentation.
@NickSeagull will be testing this against a project.
=> fix(local): move @types/nedb to dependencies

.github/workflows/lint.yml
We are manually telling all contributors to run `./scripts/check-all-the-things.sh` to run unit tests and to autoformat the code.
We are already running unit tests, why not also adding automating formatting?
Made the Lint action now run `lint:fix` and create a new PR with changes. Not sure if this will work, because you know how the CI/CD stuff works... Trial and error....
=> Add automatic ESLint fixing

packages/framework-provider-kubernetes-infrastructure/src/infrastructure/k8s-sdk/k8s-management.ts
Added an `await` when checking against the Kubernetes cluster that a resource is already deployed. 
added an `await` 🤷🏼
=> added await for resource deployed into Kubernetes checking method. 

packages/framework-provider-kubernetes-infrastructure/src/infrastructure/k8s-sdk/k8s-management.ts
In order to make the Kubernetes provider compatible with AWS EKS, we discovered that the services IP is provided using an AWS url rather than an IP. This IP is provided in a field called `hostname` under the ingress configuration. Previously we were using the property `ip` because Google Cloud clusters provide the service IP in this property. 
In this PR we are simply adding the support to get the service URL from the hostname in case that the IP field is empty
=> fix to allows service to get the ip from hostname

packages/framework-core/test/helpers/promises.test.ts, packages/framework-provider-azure/src/index.ts
This fixes an error that doesn't allow deployments to Azure.
It sets the `cosmosClient` to `{}` when the `cosmosDbConnectionString` environment variable doesn't exist because it's only supposed to exist at runtime.
Azure deployments are working now! 🚀
=> fix(azure): Azure cosmosDB error at deployment

packages/framework-provider-azure-infrastructure/src/infrastructure/arm-templates/cosmos-db-account.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/index.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/utils.ts
It fixes some issues when trying to deploy a serverless Booster app into Azure.
- The deployment zip file just contains the `.deploy/` directory content instead of all the root folder, so it's more than 10 times lighter. This avoids an issue where sometimes the upload was failing.
- Removed catch from the `deployApp` and `nukeApp` functions because it was not throwing the errors, so it was not possible to know when there was an issue.
- Disable CosmosDB free tier flag to be able to deploy several apps.
Azure Serverless deployments are working and allow performing GraphQL queries and mutations. 🚀
=> Fix azure provider infra

packages/framework-provider-aws/test/library/read-models-searcher-adapter.test.ts, packages/framework-provider-azure/src/library/searcher-adapter.ts, packages/framework-provider-azure/test/library/searcher-adapter.test.ts
Refactor to make Azure search filters compatible with the new version.
Refactor to Azure provider `searcher-adapter.ts` file.
~- [ ] Updated documentation accordingly~ not necessary
~This just makes it compatible with the simple filters, the complex filters, Arrays filters, and the filter combinators like `and`, `or` and `not` are still pending. So it doesn't finish Azure at #601 yet.~ **I ended up adding them so the PR has support for all the filters.**
=> refactor searcher-adapter to use the new filters

packages/framework-core/src/booster.ts
Right now we were ignoring the logger level
=> Build logger *after* the project configuration has been loaded

packages/framework-core/src/booster.ts
The new name is consistent with `Booster.readModel` and easier to understand, specially when showing code to others
=> Change name "Booster.fetchEntitySnapshot" by "Booster.entity"

packages/framework-provider-azure-infrastructure/src/infrastructure/utils.ts
needle (the node http client we are using) has 3 different timeouts
- `open_timeout`: (or timeout) Returns error if connection takes longer than X milisecs to establish. Defaults to 10000 (10 secs). 0 means no timeout.
- `response_timeout`: Returns error if no response headers are received in X milisecs, counting from when the connection is opened. Defaults to 0 (no response timeout).
- `read_timeout`: Returns error if data transfer takes longer than X milisecs, once response headers are received. Defaults to 0 (no timeout).
As we can see by default `response_timeout` and `read_timeout` default values mean there is no timeout. That is not the case for `open_timeout` which has a default value of 10 seconds. 
I strongly suspect this was the issue when zip deployment the very few times it …
=> Remove all needle's timeout to 0

packages/framework-provider-kubernetes/src/library/events-adapter.ts, packages/framework-provider-kubernetes/src/services/event-registry.ts, packages/framework-provider-kubernetes/src/services/read-model-registry.ts, packages/framework-provider-kubernetes/src/services/redis-adapter.ts
fixes the bug that occur when user uses _ on IDs
- Use a more appropriate separator for Redis keys
=> FIX _ redis key separator bug for ids with _

packages/framework-provider-kubernetes-infrastructure/src/index.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/index.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/k8s-sdk/k8s-management.ts
The configuration for deploy in multiple clusters is the following:
Before moving from one cluster to another we need to delete de component folder, to avoid the bug that we have with non-existing eventstore
=> added configuration for deploy in multiple clusters

packages/framework-provider-kubernetes/src/index.ts, packages/framework-provider-kubernetes/src/library/searcher-adapter.ts
Adds a ReadModel searcher-adapter which enables filtering queries on Redis.
Added the searcher adapter file instead of using a function.
Complex filters are not yet supported.
=> add searcher-adapter for redis db

docs/README.md
It seems that the local provider is currently unusable so I have temporarily removed that part. 
On the other hand, I added [this directory](https://github.com/boostercloud/examples) to the booster examples section.
- Remove local provider section
- Update booster examples.
=> doc: Remove local provider section and update Booster examples

CONTRIBUTING.md
Currently, an image from CONTRIBUTING.md is not displayed on the new documentation website.
Fix img url in CONTRIBUTING.md
=> doc: Fix img url in CONTRIBUTING.md

packages/framework-provider-aws-infrastructure/src/infrastructure/params.ts
Thes changes avoid timeouts (and, thus, losing events) and increments the speed at which events are processed
~- [ ] Updated documentation accordingly~
=> Increase AWS limits to avoid errors on high load

packages/framework-provider-aws/src/index.ts
The current timeout is 2 minutes which is too long and was causing some calls to take minutes to finish just because there was a socket error. Now, with a shorter timeout, the calls made with a socket in a bad state are retried much faster and the changes to succeed are higher within a shorter period of time
<details>
<summary>Click for more details about this issue</summary>
After a lot of investigation, we were seeing that simple DynamoDB calls (it doesn’t matter if it was “query”, “get” or “put”) were taking like 4 or 5 minutes to succeed. That was the root of the problem.
_But why did those take that long time??_
The AWS SDK has a built-in retry mechanism. When you do a DynamoDB call, for example, it will automatically redo the request if it gets an error that’s considered “retriable” …
=> Reduce DynamoDB timeout

packages/framework-types/src/config.ts
Quick fix to restore auth env vars, they're needed for rockets which modify internally the tokenVerifier object.
=> Fix: Add Auth env vars

packages/framework-integration-tests/integration/providers/kubernetes/constants.ts, packages/framework-integration-tests/integration/providers/kubernetes/deployment/deployment.integration.ts, packages/framework-integration-tests/integration/providers/kubernetes/deployment/setup.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/deploy-manager.ts, packages/framework-provider-kubernetes-infrastructure/src/infrastructure/utils.ts, packages/framework-provider-kubernetes-infrastructure/test/infrastructure/dapr-manager.test.ts, packages/framework-provider-kubernetes-infrastructure/test/infrastructure/deploy-manager.test.ts, packages/framework-provider-kubernetes/src/services/event-registry.ts
Added a verification before trying to upload any code into the cluster because in AWS the services are DNS based and the domain takes some time to propagate (around 1 min) and the deployment was failing some times because of this. 
Also added a small fix because we were obtaining the first snapshot instead of the last snapshot when we were using the read models. 
Changes in K8s provider
=> Fixed related with the K8s provider

packages/cli/src/services/dependencies.ts, packages/cli/test/services/dependencies.test.ts, packages/framework-integration-tests/integration/cli/cli.project.integration.ts
The CLI flag `--no-optional` was missing in this [PR](https://github.com/boostercloud/booster/pull/816) 
Adding the `--no-optional` flag to the `npm install --production` command.
=> fix: add CLI flag

docs/chapters/04_features.md, packages/cli/src/templates/type.ts, packages/framework-integration-tests/integration/fixtures/common/item-with-fields.ts, packages/framework-integration-tests/integration/fixtures/common/item.ts
Due to some limitations with the GraphQL API, the commands/read-models property types should be classes instead of interfaces.
* Change `boost new:type` CLI command to generate a class instead of an interface
* Modified existing tests
* Added docs for this new limitation
=> Switch interfaces to classes on new:type command

docs/chapters/04_features.md
This comment is incorrect since December 2020. Only the project files and those added to `config.assets` are deployed
=> Remove outdated comment about deployment

packages/framework-provider-local/src/library/read-model-adapter.ts, packages/framework-provider-local/src/library/searcher-adapter.ts, packages/framework-provider-local/test/library/read-model-adapter.test.ts, packages/framework-provider-local/test/library/searcher-adapter.test.ts
Modify Local provider searcher-adapter.ts to be able to use the new GraphQL filters like the rest of the providers.
Modified the provider's `searcher-adapter.ts` to make it compatible with the new format.
~- [ ] Updated documentation accordingly~ Not necessary 
Now the local provider GraphQL API is at the same state as the Azure and the K8s ones.
Closes: #601
=> Local provider GraphQL filters compatibility

.github/workflows/integration-tests.yml
Github actions integration tests are defined by consequent jobs with steps. There is a problem where when an integration test fails after deploying the stack to AWS, the rest of the steps get skipped, including the `nuke` one. This is causing that many stacks are created in AWS without being deleted after running the tests, so AWS limits are being hit.
This PR includes a solution that makes the `nuke` job run if the `deployment` step has succeeded, even if any integration test in the middle fails.
A conditional expression was added to the GitHub actions `YAML` file to make the nuke job always run when the deployment has succeeded. Also, the property `continue-on-error` is set to true, so it doesn't get skipped if any other job has failed.
~- [ ] Updated documentation accordingly~ Not …
=> GitHub actions nuke AWS stack when was deployed

packages/framework-core/src/services/graphql/graphql-query-generator.ts
Fix to avoid excluding enums as `GraphQLJSONObject` types
Now checks when the type at compilation time is just an `object` type, setting then the `GraphQLJSONObject` by default
=> include custom object types like enums

.github/workflows/integration-tests.yml
We're finally disabling k8s tests temporary, there's already an issue created to solve this when we get a chance
=> Temporary disable k8s integration tests

packages/framework-provider-aws-infrastructure/src/index.ts, packages/framework-provider-aws-infrastructure/test/index.test.ts
Related issue: https://github.com/boostercloud/booster/issues/597
Currently, when deploying a booster application, and if a rocket throws an error, the CLI just keeps printing the next steps, when the deployment failed (it just shows an "X"):
```bash
boost deploy -e development
ℹ boost deploy [development] 🚀
ℹ Bootstraping the following environment: {"name":"Default environment","account":"<id>","region":"eu-west-1"}
⏳  Bootstrapping environment aws://<id>/eu-west-1...
my-app-dev-toolkit: creating CloudFormation changeset...
[██████████████████████████████████████████████████████████] (3/3)
✅  Environment aws://<id>/eu-west-1 bootstrapped.
ℹ Deploying my-app-dev on environment development
✖ <------ IT ONLY SHOWS THIS "X"
✔ Deploying
✔ Cleaning up deployment files
ℹ Deployment complete! …
```
=> Show rocket errors on the CLI

packages/application-tester/src/index.ts, packages/framework-integration-tests/integration/provider-unaware/load/entities-are-correctly-reduced.load.ts, packages/framework-integration-tests/package.json, packages/framework-provider-local/src/library/graphql-adapter.ts, packages/framework-provider-local/test/library/graphql-adapter.test.ts
With this PR you can now use authorization in your local provider. You can use any auth rocket for that.
The local provider was ignoring the token that was being sent in the request. After passing it through the core, all the authorization features are available.
=> Allow the local provider to use all the authorization features

docs/chapters/02_getting-started.md
Added a paragraph to the documentation warning about some things to look out for when setting up credentials and environment variables for multiple AWS profiles. The warning refers to a known problem with the AWS CLI that has been described before [elsewhere](https://github.com/aws/aws-cli/issues/3304#issuecomment-386308416).
=> Documentation: Multiple AWS profiles

docs/chapters/04_features.md
I'm just waiting for confirmation from discord but I think the read events API only works with the AWS provider. I'm just adding this limitation to the docs.
=> Modify read events API docs

packages/framework-core/src/services/graphql/graphql-type-informer.ts
The latest release improved the GraphQL schema generation by adding `GraphQLNonNull` to elements of arrays. 
However, this causes arrays in *input* types to result in `JSONObject` instead of the specific type. (https://github.com/boostercloud/booster/commit/e9906b4aad3dfdd97832fe2111343b3647cf467a)
Example:
It also breaks PR https://github.com/boostercloud/booster/pull/890 which also fixes some `JSONObject` types, returning specific types instead.
```
[Booster]  Error: The type of UpsertDossierInput.parties must be Input Type but got: [DossierParty!].
```
This PR should improve the input types again:
=> fix: correct input types for non-nullable arrays

packages/framework-provider-aws/src/library/read-models-adapter.ts
Added a comment in the source code to explain why we're doing consistent reads in Read Models, which are defined as eventually consistent objects. Created issue #931 to address this in the future.
=> Added a TODO comment in the AWS' read model adapter

packages/framework-core/src/booster.ts, packages/framework-core/test/booster.test.ts
Closes #896 
Closes #918 
Currently, Booster.entity returns a `EventEnvelope` when it should actually return the `Entity`.
Changes src/booster.ts:149 from `createInstance(entityClass, entitySnapshotEnvelope)` to `createInstance(entityClass, entitySnapshotEnvelope.value)`
Changes tests/booster.test.ts:213 from `replace(EventStore.prototype, 'fetchEntitySnapshot', fake.returns({  id: '42'  }))` to `replace(EventStore.prototype, 'fetchEntitySnapshot', fake.returns({ value: { id: '42' } }))` to fix core tests
=> fix(core): Ensure Booster.entity returns an entity instead of envelope

package-lock.json, package.json, packages/framework-common-helpers/package.json, packages/framework-common-helpers/src/index.ts, packages/framework-common-helpers/src/run-command.ts, packages/framework-integration-tests/integration/helper/cli-helper.ts, packages/framework-integration-tests/integration/provider-specific/azure/deployment/.mocharc.yml, packages/framework-integration-tests/integration/provider-specific/azure/deployment/deployment.integration.ts, packages/framework-integration-tests/integration/provider-specific/azure/deployment/setup.ts, packages/framework-integration-tests/integration/provider-specific/azure/nuke/.mocharc.yml, packages/framework-integration-tests/integration/provider-specific/azure/nuke/nuke.integration.ts, packages/framework-integration-tests/integration/provider-specific/azure/nuke/setup.ts, packages/framework-integration-tests/integration/provider-specific/local/setup.ts, packages/framework-integration-tests/integration/provider-specific/local/start/setup.ts, packages/framework-integration-tests/integration/provider-unaware/load/artillery-executor.ts, packages/framework-integration-tests/package-lock.json, packages/framework-integration-tests/package.json, packages/framework-integration-tests/src/config/config.ts, packages/framework-provider-azure-infrastructure/src/index.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/helper/az-cli-helper.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/types/resource-group.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/types/service-principal.ts, packages/framework-provider-azure-infrastructure/src/test-helper/azure-test-helper.ts, packages/framework-provider-kubernetes-infrastructure/package-lock.json, packages/framework-provider-kubernetes-infrastructure/src/index.ts, packages/framework-provider-local-infrastructure/src/index.ts
Implement deploy and nuke tests for azure and make the integration suite run on the deployed Azure stack.
1. Add Azure Deploy Integration Test
1. Add Azure Nuke Integration Test
1. Fix bug creating infrastructure on azure, k8s, and local providers (related to this [PR](https://github.com/boostercloud/booster/pull/957))
1. Add has-tostringtag package to avoid  `eslint` errors
1. Refactor run-command.ts (move it to framework-common-helpers)
This change increases the `Nuke` test timeout to avoid issues with Azure.
Not done:
1. Update Github workflow. Pending improvement `Nuke` performance
=> Azure integration tests

package-lock.json, packages/framework-provider-azure-infrastructure/package.json, packages/framework-provider-azure-infrastructure/src/index.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/stacks/application-stack.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/stacks/event-handler-function.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/stacks/graphql-function.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/stacks/schedules-functions.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/types/functionDefinition.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/utils.ts, packages/framework-provider-azure-infrastructure/test/expect.ts, packages/framework-provider-azure-infrastructure/test/infrastructure/stacks/event-handler-functions.test.ts, packages/framework-provider-azure-infrastructure/test/infrastructure/stacks/graphql-functions.test.ts, packages/framework-provider-azure-infrastructure/test/infrastructure/stacks/schedules-functions.test.ts, packages/framework-provider-azure/src/index.ts, packages/framework-provider-azure/src/library/scheduled-adapter.ts, packages/framework-provider-local-infrastructure/src/index.ts
There’s a Scheduled Commands feature in AWS that takes a typical cron string and triggers a command on a schedule instead of making it wait for a request. This feature is now supported in Azure
* Add PackageAzureFunction classes for: GraphQL, EventHandler and ScheduleCommands function
* Refactor Azure/ApplicationStackBuilder class
* Refactor Azure/FunctionDefinition
* Add Azure rawScheduledInputToEnvelope
* Update Azure Provider to include Azure/rawScheduledInputToEnvelope call
=> feat(azure): Add Azure Scheduled Commands support

docs/chapters/02_getting-started.md
Many users may not be familiar with how or where to work with AWS environment variables. For example, how are these different than .env set variables?)
Updated documentation to hopefully –
* make it clearer on where to set a variable like AWS_PROFILE
* add detail in warning about how / when to check and unset AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID variables
* added detail that setting AWS_PROFILE needs to be manually done for each deploy/nuke
* added notes for a workaround to tie a profile to an environment via package scripts
=> Docs: Clarify how to use multiple AWS profiles

packages/framework-integration-tests/integration/helper/app-helper.ts, packages/framework-integration-tests/integration/provider-specific/azure/deployment/deployment.integration.ts, packages/framework-integration-tests/integration/provider-specific/azure/nuke/nuke.integration.ts
Improve Azure integration test
Refactor BOOSTER_ENV check to fail if it's not set
=> Fail if env variable is not set on Azure integration tests

package-lock.json, packages/framework-core/src/booster-auth.ts, packages/framework-core/src/booster-token-verifier.ts, packages/framework-core/src/services/graphql/graphql-query-generator.ts, packages/framework-core/test/booster-auth.test.ts, packages/framework-core/test/booster-command-dispatcher.test.ts, packages/framework-core/test/booster-events-reader.test.ts, packages/framework-core/test/booster-graphql-dispatcher.test.ts, packages/framework-core/test/booster-read-model-reader.test.ts, packages/framework-core/test/booster-register-handler.test.ts, packages/framework-core/test/booster-token-verifier.test.ts, packages/framework-core/test/services/graphql/graphql-generator.test.ts, packages/framework-core/test/services/graphql/graphql-query-generator.test.ts, packages/framework-core/test/services/graphql/websocket-protocol/graphql-websocket-protocol.test.ts, packages/framework-integration-tests/integration/provider-unaware/end-to-end/events.integration.ts, packages/framework-integration-tests/integration/provider-unaware/functionality/event-handlers.integration.ts, packages/framework-provider-aws/test/library/connections-adapter.test.ts, packages/framework-types/src/envelope.ts
Allow JWT tokens with an array of Roles 
UserEnvelope now map the JWT roles to an Array of roles
=> Allow arrays of roles on jwt tokens

docs/chapters/05_going-deeper.md
Updates the documentation with information explaining how to publish a rocket to an NPM repository.
- Updated some sentences where it said that only AWS was supported. Now Azure and Local providers are also supported in an experimental phase.
- Added a new section describing how to publish a rocket to NPM.
- Added the new Azure & Local webhook Rocket to the list of available rockets.
=> Update docs with information on how to publish a rocket

docs/chapters/03_booster-architecture.md, docs/chapters/07_frequently-asked-questions.md
Update documentation reflect changes of https://github.com/boostercloud/booster/pull/724.
Added to FAQ because the video tutorials on the Youtube channel use the old notation which means that people might get confused in the future.
=> Update documentation regarding fetchEntitySnapshots -> entity rename

package-lock.json, packages/framework-core/src/booster-logger.ts, packages/framework-core/src/booster.ts, packages/framework-core/test/booster-logger.test.ts, packages/framework-core/test/booster-register-handler.test.ts, packages/framework-core/test/services/event-store.test.ts, packages/framework-core/test/services/graphql/graphql-generator.test.ts, packages/framework-core/test/services/read-model-store.test.ts, packages/framework-types/src/config.ts
This PR will allow Booster users to change the default logger and specify a custom one. The custom logger implements the `Logger` interface:
```typescript
interface Logger {
debug(message?: any, ...optionalParams: any[]): void;
info(message?: any, ...optionalParams: any[]): void;
error(message?: any, ...optionalParams: any[]): void;
}
```
Configuration example:
```typescript
Booster.configure('prod', (config: BoosterConfig): void => {
config.appName = 'awesome-app'
config.providerPackage = '@boostercloud/framework-provider-aws'
config.logPrefix = '<My awesome app > '
config.logLevel = Level.debug
config.logger = {
debug: (message: string, ...optionalParameters: any[]) => {
// ... Call to your log thing....
},
info: (message: string, ...optionalParameters: any[]) => {
},
error: (message: …
```
=> feat: Added custom logger configuration

.vscode/launch.json, packages/framework-core/src/booster-logger.ts, packages/framework-core/src/booster.ts, packages/framework-core/test/booster-logger.test.ts, packages/framework-core/test/booster-register-handler.test.ts, packages/framework-core/test/services/event-store.test.ts, packages/framework-core/test/services/graphql/graphql-generator.test.ts, packages/framework-core/test/services/read-model-store.test.ts
Minor change to publish the configured `Booster.logger` object (with a fallback to console.log)
- Replaced the private static property `logger` in the `Booster` singleton by a getter that proxies the logger defined in the current `Booster.config` object.
- It falls back to `console.log` when no logger is configured.
=> Publish `Booster.logger` for easy access along the core and apps

.github/workflows/integration-tests.yml, .github/workflows/lint.yml, .github/workflows/publish.yml, .github/workflows/tests.yml, packages/framework-core/src/services/read-model-store.ts, packages/framework-core/test/services/read-model-store.test.ts
Fixes two bugs:
Removed error and just log a warning if a joining key doesn't exists in read models
Avoid passing an empty object instance if the entity doesn't exists into the read models
=> removed error if join key is not valid and avoid to pass empty instance to readmodels

packages/framework-integration-tests/integration/provider-unaware/end-to-end/read-models.integration.ts, packages/framework-provider-azure/src/helpers/query-helper.ts, packages/framework-provider-azure/test/helpers/query-helper.test.ts, packages/framework-provider-local/src/library/read-model-adapter.ts, packages/framework-provider-local/src/library/searcher-adapter.ts, packages/framework-provider-local/src/services/read-model-registry.ts, packages/framework-provider-local/test/library/read-model-adapter.test.ts, packages/framework-provider-local/test/library/searcher-adapter.test.ts
* Add support for paginated queries for Local Providers
* Add support for `includes` queries with objects for Local Providers
Now it is possible to run paginated queries on Local Providers:
```graphql
{
ListCartReadModels(filter: { cartItems: { includes: { productId: "f5030252-be8f-4873-b713-501b1945f552", quantity: 2 } } }, limit: 500) {
items {
id
cartItems 
checks
shippingAddress {
firstName
}
payment {
cartId
}
cartItemsIds
}
cursor
}
}
```
Now it's possible to use `includes` clause with objects in LocalProvider:
```graphql
{ cartItems: { includes: { productId: mockProductId, quantity: 2 } } }
```
**LocalProvider** paginated queries now return correct objects for pagination. You may need to update your application to support this. Example:
```graphql
items: [CartReadModel]
cursor: …
```
=> Add paginated queries and "includes object" for Local Providers

docs/chapters/03_booster-architecture.md, packages/framework-core/src/decorators/projects.ts, packages/framework-core/src/services/read-model-store.ts, packages/framework-core/test/services/read-model-store.test.ts, packages/framework-integration-tests/integration/provider-unaware/end-to-end/read-models.integration.ts, packages/framework-integration-tests/src/commands/create-pack.ts, packages/framework-integration-tests/src/entities/pack.ts, packages/framework-integration-tests/src/events/pack-created.ts, packages/framework-integration-tests/src/read-models/product-read-model.ts, packages/framework-types/src/concepts/projection-metadata.ts, packages/framework-types/src/config.ts
This PR is related to the need of using array fields in the `joinKey` for read model projections. The implemented behavior is to execute the projection for all the UUIDs in the array independently. So we will call the projection logic for each read model in the array.
The change is backward compatible with previous projections methods, so no changes are required in projects using the previous version.
- Update `joinKeyForProjection` method to always return `Array<UUID>` or `undefined` in case the key is missing
- Updated `project` method to process and call `applyProjectionToReadModel` for each UUID in the `joinKey` array
- Add an optional parameter to the `projectionFunction` call in order to pass the current readModelID we are processing from the array
- Adding type checking in …
=> Issue 1053: Add Array joinKey support in read model projections

packages/framework-common-helpers/src/retrier.ts
Addresses Issue #1010
- typecasted error from unknown to Error in retries.ts present in package framework-common-helpers
=> fix: typecasted e from unknown to Error

.vscode/launch.json, docs/chapters/05_going-deeper.md, packages/framework-core/src/booster-graphql-dispatcher.ts, packages/framework-core/test/booster-graphql-dispatcher.test.ts, packages/framework-types/src/config.ts
Added a flag to enable/disable graphQL introspection (a.k. a. get the schema) in `Booster.Config`
- Added flag to `Booster.Config`
- Modified graphQL dispatch to use the flag and return an error to tell the user what's happening with the schema
- Added Tests
- Added a new configuration to `launch.json` to launch the local debugger using the sandbox app under the integration test package
=> added a configuration to control the availability of graphQL instrospection

packages/framework-core/src/booster-graphql-dispatcher.ts
Renamed a method wrongly called `verifyTokenFromEnvelop` as the correct wording `verifyTokenFromEnvelope`. No other files are affected, as it is a private function.
=> Minor typo fix in graphQL Dispatcher

packages/framework-core/src/services/graphql/query-helpers/graphql-query-sort-builder.ts
Similar to the filter generation, UUID and Date need to be filtered because they have typeGroup `Class` and we don't want `getClassMetadata` to be executed.
=> fix: add UUID and Date types to GraphQL sort generator

packages/framework-core/src/booster-event-dispatcher.ts, packages/framework-core/src/services/event-store.ts, packages/framework-core/src/services/raw-events-parser.ts, packages/framework-core/test/services/event-store.test.ts, packages/framework-core/test/services/raw-events-parser.test.ts
This PR makes event processing concurrent in order to avoid cancelling event processing for some entities when a reducer for an unrelated entity fails. 
Also it makes `fetchEntitySnapshot` cache the generated snapshots so they are available for the next time someone requests it.
=> Make event processing concurrent + cache snapshots

package-lock.json, packages/framework-core/package.json, packages/framework-core/src/services/graphql/graphql-type-informer.ts, packages/framework-core/src/services/graphql/query-generators/graphql-query-events-generator.ts, packages/framework-core/src/services/graphql/query-generators/graphql-query-listed-generator.ts, packages/framework-core/src/services/graphql/query-helpers/graphql-query-filter-arguments-builder.ts, packages/framework-core/test/services/graphql/graphql-query-generator.test.ts, packages/framework-core/test/services/graphql/graphql-type-informer.test.ts, packages/framework-integration-tests/integration/provider-unaware/end-to-end/cart.integration.ts, packages/framework-integration-tests/integration/provider-unaware/end-to-end/entities.integration.ts, packages/framework-integration-tests/integration/provider-unaware/end-to-end/events.integration.ts, packages/framework-integration-tests/integration/provider-unaware/end-to-end/read-models.integration.ts, packages/framework-integration-tests/integration/provider-unaware/functionality/schema.filter.integration.ts, packages/framework-integration-tests/integration/provider-unaware/functionality/schema.search.integration.ts, packages/framework-integration-tests/src/commands/create-product.ts, packages/framework-integration-tests/src/commands/update-product.ts, packages/framework-integration-tests/src/entities/product.ts, packages/framework-integration-tests/src/events/product-created.ts, packages/framework-integration-tests/src/events/product-updated.ts, packages/framework-integration-tests/src/migrations/read-models/ProductReadModel/migrations.ts, packages/framework-integration-tests/src/read-models/product-read-model.ts
For unrecognized types, we were using a scalar which enforced the usage of a **strictly JSON Object**. We found some scenarios where that approach didn't work i.e. if we have a `productType: 'A' | 'B' | 'C'`, that productType was resolved as a strictly JSON Object scalar, which later on caused some problems in mutations because the productType isn't a real JSON Object, in fact, is a string, so the internal serializer couldn't parse the value. 
Added a loosely JSON type as a fallback which works as an ANY type. Instead of creating our own type, we are using the one that works from https://www.graphql-scalars.dev/     
For more information about custom scalar types:
* https://kamranicus.com/handling-multiple-scalar-types-in-graphql/
* …
=> fix: added default graphQL JSON scalar type as fallback for unrecognized types

packages/cli/src/common/sandbox.ts
Not only on the `synth` process but each time the sandbox project is created we need to copy not only the package.json but also the package-lock.json file
See https://github.com/boostercloud/booster/issues/1135 for more info.
=> Synth operation should take into account project's package-lock.json

packages/framework-provider-local-infrastructure/src/index.ts
The payload limit of the local provider is currently the express default (100kb).
Every other provider has a higher limit (aws: 6mb, azure: unlimited, kubernetes: unlimited?) which can lead to friction between local tests and the production environment.
This PR increases the payload limit of the local provider to the next smallest limit, i.e. AWS with 6mb.
Ref: #1105
I set the express payload to 6mb as described [here](https://stackoverflow.com/a/19965089).
No tests as the local provider doesn't seem to have any tests yet.
I also haven't verified that this actually increases the limit correctly to 6mb, by using it myself yet. I'm happy to wait to merge until I at least tried it out locally.
=> fix(local): increase payload limit to aws lambda limit (6mb) [#1105]

packages/framework-provider-local-infrastructure/src/index.ts
#1150  (aka. #1155) successfully increased the payload size of the local provider to the next smallest one, i.e. AWS at 6mb.
This PR fixes the warning message that pops up when starting the local provider that is due to express [requiring that the `extended` flag is set explicitly as it is due to change for its the next major version](https://stackoverflow.com/a/25471936).
This PR sets the `extended` flag to `true`, which allows for rich objects and arrays to be encoded into the URL-encoded format, allowing for a JSON-like experience with URL-encoded. For more info see [the docs here](http://expressjs.com/en/api.html#express.urlencoded).
Explicitly set express body-parser's `extended` flag to `true` to avoid a warning message when starting the local provider.
I tried it out locally this …
=> fix(local): express body-parser extended warning

common/config/rush/pnpm-lock.yaml, packages/cli/package.json, packages/framework-core/package.json, rush.json, tools/stack-cleaner/.eslintignore, tools/stack-cleaner/.eslintrc.js, tools/stack-cleaner/README.md, tools/stack-cleaner/package.json, tools/stack-cleaner/src/aws.ts, tools/stack-cleaner/src/cloud.ts, tools/stack-cleaner/src/common.ts, tools/stack-cleaner/src/index.ts, tools/stack-cleaner/src/main.ts, tools/stack-cleaner/tsconfig.eslint.json, tools/stack-cleaner/tsconfig.json, tsconfig.eslint.json
We had some stale stacks in our AWS account so I added a script that we can reuse to cleanup those in the future. Also, it is easily extendable to Azure as well.
Code is a bit of a mess, but given its importance (just a side tool) I think it is good to have it here
=> [skip ci] Added a helper stack cleaner tool to cleanup stale stacks 

common/changes/@boostercloud/framework-core/fix-archiver-and-yaml-dependencies-were-required-after-generating-a-new-project_2022-11-10-15-20.json, common/config/rush/pnpm-lock.yaml, packages/framework-integration-tests/package.json, packages/framework-provider-aws-infrastructure/package.json
Projects generated with version 1.0.1 were displaying an error like this when trying to deploy to AWS:
```
[2022-11-10T15:13:19.800Z] boost deploy -e production
[2022-11-10T15:13:19.800Z] Error: The AWS infrastructure package could not be loaded. The following error was thrown: Cannot find module 'yaml'
...
[2022-11-10T15:13:19.800Z] - Please ensure that one of the following actions has been done:
[2022-11-10T15:13:19.800Z]   - It has been specified in your "devDependencies" section of your "package.json" file. You can do so by running 'npm install --save-dev @boostercloud/framework-provider-aws-infrastructure'
[2022-11-10T15:13:19.800Z]   - Or it has been installed globally. You can do so by running 'npm install -g @boostercloud/framework-provider-aws-infrastructure'
```
This PR adds a …
=> Fixed missing dependency errors when deploying to AWS.

common/changes/@boostercloud/framework-core/fix-readable-error-messages-cli_2022-12-15-16-13.json, common/config/rush/pnpm-lock.yaml, packages/cli/src/common/errors.ts, packages/cli/src/services/config-service.ts, packages/cli/src/services/file-system/index.ts, packages/cli/src/services/file-system/live.impl.ts, packages/cli/src/services/package-manager/common.ts, packages/cli/src/services/package-manager/index.ts, packages/cli/src/services/package-manager/rush.impl.ts, packages/cli/src/services/process/index.ts, packages/cli/src/services/process/live.impl.ts, packages/cli/src/services/project-initializer.ts, packages/cli/test/services/file-system/live.test.ts, packages/cli/test/services/package-manager/live.test.ts, packages/cli/test/services/package-manager/npm.test.ts, packages/cli/test/services/package-manager/pnpm.test.ts, packages/cli/test/services/package-manager/rush.test.ts, packages/cli/test/services/package-manager/yarn.test.ts, packages/cli/test/services/process/live.test.ts, packages/framework-types/src/effect/index.ts
After 1.0, the CLI error messages became a bit more unreadable, because they were being stringified. This PR fixes that
Reworked error bubbling as well as printing
=> fix(cli): Make error messages more readable

website/docs/03_features/03_data-migrations.md
Improved the migrations section of the documentation:
* Added an introduction explaining the purpose and types of migrations in Booster Framework (schema migrations and data migrations)
* Clarified that schema migrations are applied lazily, meaning they are performed on the fly whenever an event or entity is loaded
* Added an example of a schema migration class and explained the `@ToVersion` decorator
* Added a data migration class example and explained the `@DataMigration` decorator and the `Booster.migrateEntity` method
* Clarified that data migrations are run in a specific order, as specified by the order value in the `@DataMigration` decorator
Overall, these changes aim to provide a clearer and more comprehensive explanation of the migration mechanisms in Booster Framework and how to …
=> Improved migrations documentation

.github/actions/build/action.yml, .github/actions/test-integration-run-one/action.yml, .github/workflows/re_test-integration-aws.yml, .github/workflows/re_test-integration-azure.yml, .github/workflows/re_test-integration-cli.yml, .github/workflows/re_test-integration-local.yml
We spend like 10 minutes for installing and building for each job in the CICD, this PR mitigates that by caching.
Caches the Rush project before building
=> chore(cicd): Try caching build and dependencies

.github/workflows/wf_check-changes.yml, .github/workflows/wf_check-lint.yml, .github/workflows/wf_publish-npm.yml, .github/workflows/wf_test-unit.yml, website/docs/03_architecture/06_read-model.mdx
This pull request updates the documentation for using getters in read models in the Booster Framework. It includes an explanation of how getters can be used to allow nested queries and return calculated values in the GraphQL API. It also includes an example of how to use getters to retrieve related read models, as well as an example of returning a calculated value such as the current time stamp of the request.
=> Added documentation for nested queries using getters

.vscode/launch.json, booster.code-workspace, common/changes/@boostercloud/framework-core/fix-issue-1307-backwards-compatibility-with-projects-that-define-a-compile-script_2023-01-23-20-32.json, common/config/rush/pnpm-lock.yaml, packages/cli/src/services/config-service.ts, packages/cli/src/services/file-system/index.ts, packages/cli/src/services/file-system/live.impl.ts, packages/cli/src/services/package-manager/common.ts, packages/cli/src/services/package-manager/index.ts, packages/cli/src/services/package-manager/rush.impl.ts, packages/cli/test/services/config-service.test.ts, packages/cli/test/services/file-system/test.impl.ts, packages/cli/test/services/package-manager/npm.test.ts, packages/cli/test/services/package-manager/pnpm.test.ts, packages/cli/test/services/package-manager/rush.test.ts, packages/cli/test/services/package-manager/test.impl.ts, packages/cli/test/services/package-manager/yarn.test.ts, packages/framework-integration-tests/integration/provider-unaware/cli/cli.build.integration.ts
Now When Booster CLI commands need to build the user project, Booster will check if there's a "compile" script defined in the user's package.json file. If it exists, it will run it instead of the default "build" script.
This is a fallback to provide backwards compatibility with projects created with previous versions of Booster that used this "compile" script by default instead.
This PR closes #1307
~Updated documentation accordingly~
=> Implemented a fallback to check the existence of a 'compile' command in the project package.json file for backwards compatibility

website/docs/03_architecture/02_command.mdx, website/docs/03_architecture/03_event.mdx, website/docs/03_architecture/04_event-handler.mdx, website/docs/03_architecture/05_entity.mdx, website/docs/03_architecture/06_read-model.mdx
- Change spelling from "Bosoter" to "Booster" on several documentation pages.
=> Fix: Change spelling from "Bosoter" to "Booster" in Booster docs

common/changes/@boostercloud/framework-core/azure-is-no-longer-experimental_2023-02-18-23-11.json, common/changes/@boostercloud/framework-core/azure-is-no-longer-experimental_2023-02-22-20-01.json, packages/cli/src/common/provider.ts, packages/cli/test/common/provider.test.ts, website/docs/10_going-deeper/infrastructure-providers.mdx, website/docs/10_going-deeper/rockets.mdx
It's been a while since many people are using the Azure implementation with no issues, so this PR puts it in the place it deserved, as a fully supported provider.
Removed all the misleading notes claiming that Azure support is experimental
=> Azure no longer described as experimental

.github/actions/test-integration-run-one/action.yml, common/changes/@boostercloud/framework-core/support_uuid_contains_filters_2023-03-16-10-39.json, packages/framework-core/src/services/graphql/query-helpers/graphql-query-filter-arguments-builder.ts, packages/framework-integration-tests/integration/provider-unaware/end-to-end/read-models.integration.ts
Add `contains` and `beginsWith` filters to UUID fields
Update graphQL to support `contains` and `beginsWith` filters to UUID fields
=> Support UUID contains filters

common/changes/@boostercloud/framework-core/fix-findbyid-readmodel-instance_2023-05-24-11-08.json, packages/framework-core/src/booster-read-models-reader.ts
When querying a ReadModel list, the ReadModels are returned as instances. When a ReadModel is queried by id, this is not the case. As a consequence, getters do not work when querying by id. 
When querying a ReadModel by id, an instance is not returned so the getters work.
=> Return readModel instance when querying by id

common/changes/@boostercloud/framework-core/feature-fix_aws_idempotency_2023-06-26-10-49.json, packages/framework-provider-aws/src/library/events-adapter.ts
Fix DynamoDB call in `storeSnapshot` by ensuring it is idempotent
This fixes errors when eventHandlers are accessing entities via `Booster.entity` and also attempting to cache snapshots
- Removed ConditionExpression from dyanmoDB call to ensure idempotency
=> fix(framework-provider-aws): ensure storeSnapshot is idempotent

common/changes/@boostercloud/framework-core/local_concurrency_2023-06-06-14-44.json, packages/framework-integration-tests/integration/provider-unaware/end-to-end/read-model-concurrency.integration.ts, packages/framework-integration-tests/src/commands/add-concurrency.ts, packages/framework-integration-tests/src/commands/get-concurrency.ts, packages/framework-integration-tests/src/entities/concurrency.ts, packages/framework-integration-tests/src/events/concurrency-persisted.ts, packages/framework-integration-tests/src/read-models/concurrency-read-model.ts, packages/framework-integration-tests/src/read-models/other-concurrency-read-model.ts, packages/framework-provider-azure/src/library/read-model-adapter.ts, packages/framework-provider-local/src/library/read-model-adapter.ts, packages/framework-provider-local/src/services/read-model-registry.ts, packages/framework-provider-local/test/helpers/read-model-helper.ts, packages/framework-provider-local/test/library/read-model-adapter.test.ts, packages/framework-provider-local/test/services/read-model-registry.test.ts
Add Local Provider optimistic concurrency support
=> Add Local Provider optimistic concurrency support

website/src/components/BoosterChat/BoosterChat.tsx, website/src/components/CustomSidebarItem.jsx, website/src/theme/DocSidebarItem/index.js, website/src/theme/NavbarItem/CustomNavbarItem.tsx, website/src/theme/NavbarItem/NavbarNavLink.js
Made some minor refactoring. Mainly the usage of optional changing for shorter syntax.
=> Removed some redundant code

packages/framework-provider-aws/test/library/read-models-searcher-adapter.test.ts
- Changed expected input for for the 1 failing test in `@boostercloud/framework-provider-aws`, there was a change in the upgrade PR but the expected input wasn't changed, making the test fail
=> AWS unit tests now pass after changing expected input

packages/framework-provider-azure-infrastructure/src/infrastructure/synth/terraform-function-app.ts
Upgrade Azure functions nodejs runtime to v18 and change function runtime version to 4. This last thing is necessary because [function runtime version 3 does not support nodejs v18 or higher](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=javascript%2Cwindows%2Cazure-cli&pivots=nodejs-model-v4#supported-versions:~:text=GA-,4.x,20.x%20(Preview)%2C%2018.x%2C%2016.x%2C%2014.x,-Requires%20a%20specific)
**IMPORTANT**: this means existing apps that want to upgrade will need to [migrate Azure fucntions](https://learn.microsoft.com/en-us/azure/azure-functions/migrate-version-3-version-4?tabs=net6-isolated%2Cazure-cli%2Cwindows&pivots=programming-language-javascript)
- Changed Azure functions runtime to nodejs v18
- Changed function runtime version to 4
=> Azure functions nodejs runtime changed to v18 and function runtime version to 4

common/changes/@boostercloud/framework-core/improve_error_messages_2023-10-02-13-12.json, packages/framework-core/src/services/event-store.ts, packages/framework-provider-azure/src/library/read-model-adapter.ts
When reducing an event class the error message is class not found in undefined. This error doesn’t provides enough information to know what happened. We need to at least add information about the class we are looking for at least
If a ReadModel table is not added to the database Booster throw a generic error. We need to provide information to identify this error
=> Improve error messages

CONTRIBUTING.md
I have corrected a documentation typo in the `CONTRIBUTING.md` file. The original text mentioned "rust rest," which has been updated to the correct "rust test" to provide accurate and clear instructions.
Closes #1448
=> Fix documentation typo in CONTRIBUTING.md

common/changes/@boostercloud/framework-core/fix_event_api_events_notifications_not_found_2023-10-02-13-14.json, common/config/rush/pnpm-lock.yaml, packages/framework-core/src/booster-event-search.ts, packages/framework-core/src/booster.ts, packages/framework-core/test/booster.test.ts, packages/framework-integration-tests/src/common/custom-logger.ts, packages/framework-integration-tests/src/common/custom-tracer.ts, packages/framework-integration-tests/src/config/config.ts, packages/framework-types/src/envelope.ts
When we use the event API to get events Booster try to creates instances from them. This could cause issues if the event class had been removed. If the event class doesn’t exist Booster should not create the instance and the content will be a plain object
Also, when we use the event API to get notifications events Booster is not able to find the event class. Also, if the class doesn’t exist Booster should not fail but keep the event as a plain object.
=> Fix event api for events and notifications not found

website/docs/10_going-deeper/data-migrations.md
Docs show `@Migrates` as the annotation to use for schema migrations, but that's not the correct one. This PR fixes it to indicate it's `@SchemaMigration` the one to use.
=> Fix annotation for schema migrations in data-migrations.md

common/changes/@boostercloud/framework-core/support_graphql_fragments_2024-06-13-13-43.json, packages/framework-core/src/services/graphql/graphql-generator.ts, packages/framework-integration-tests/integration/provider-unaware/end-to-end/read-models.integration.ts
* Fixes support for [GraphQL fragments](https://graphql.org/learn/queries/#fragments) after the changes introduced in v2.11
=> Support GraphQL fragments

.github/workflows/re_test-integration-azure.yml, .github/workflows/wf_test-integration.yml, common/changes/@boostercloud/framework-core/calculated_fields_2024-07-08-19-05.json, common/config/rush/pnpm-lock.yaml, packages/cli/test/commands/stub/publish.test.ts, packages/cli/test/services/stub-publisher.test.ts, packages/framework-common-helpers/package.json, packages/framework-common-helpers/src/instances.ts, packages/framework-common-helpers/test/instances.test.ts, packages/framework-core/src/booster-read-models-reader.ts, packages/framework-core/src/decorators/read-model.ts, packages/framework-core/test/booster-read-models-reader.test.ts, packages/framework-core/test/decorators/read-model.test.ts, packages/framework-core/test/services/graphql/graphql-query-generator.test.ts, packages/framework-integration-tests/integration/provider-unaware/end-to-end/read-models.integration.ts, packages/framework-integration-tests/src/commands/cart-my-address.ts, packages/framework-integration-tests/src/read-models/cart-read-model.ts, packages/metadata-booster/src/metadata-types.ts, website/docs/03_architecture/06_read-model.mdx
Due to the changes introduced in version [2.11.0](https://github.com/boostercloud/booster/releases/tag/v2.11.0), this PR introduces the `@CalculatedField` decorator for read model fields, which are calculated using getters using other properties of the read model. e.g.,
```typescript
@ReadModel({
authorize: 'all',
})
export class PersonReadModel {
public constructor(
readonly id: UUID,
readonly firstName: string,
readonly lastName: string
) {}
@CalculatedField(['firstName', 'lastName'])
public get fullName(): Promise<string> {
return Promise.resolve(`${this.firstName} ${this.lastName}`)
}
}
```
This decorator receives a list of the read model's properties as an input parameter. The calculated field uses these properties to calculate its value. The decorator ensures that these properties …
=> Calculated fields

common/changes/@boostercloud/framework-core/ws_version_bump_2024-07-25-19-50.json, common/config/rush/pnpm-lock.yaml, packages/application-tester/package.json, packages/framework-core/package.json, packages/framework-integration-tests/package.json, packages/framework-provider-local/package.json, packages/framework-types/package.json
This PR fixes vulnerability [CVE-2024-37890](https://nvd.nist.gov/vuln/detail/CVE-2024-37890) found in the [ws](https://github.com/websockets/ws) library which is listed as a dependency in several Booster packages.
* Bump ws version from 8.12.0 to 8.17.1.
=> fix: ws dependency vulnerability

common/changes/@boostercloud/framework-core/fix_nested_arrays_2024-09-24-21-22.json, common/config/rush/pnpm-lock.yaml, packages/framework-provider-azure-infrastructure/package.json, packages/framework-provider-azure-infrastructure/src/infrastructure/synth/application-synth.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/synth/terraform-containers.ts, packages/framework-provider-azure-infrastructure/src/infrastructure/synth/terraform-cosmosdb-database.ts, packages/framework-provider-azure/package.json, packages/framework-provider-azure/src/helpers/query-helper.ts, packages/framework-provider-azure/test/helpers/query-helper.test.ts, website/docs/06_graphql.md
The changes in this PR fix some issues when selecting fields in read model objects that are nested deeply. Previously, if one were to select a field from an object in an array nested deeper than a top-level property, e.g., `['foo.bar.arr[].id']`, it would generate the wrong SQL code. To keep things simple, when this case is encountered, it will retrieve all the properties of the objects in the array.
* Modify `buildProjections` and add a `preprocessProjections` method to the Cosmos query helper to identify and alter the projections with deeply nested arrays.
=> Fix read model queries when selecting deeply-nested arrays

common/changes/@boostercloud/framework-core/remove_cdktf_dependency_2024-10-08-12-24.json, common/config/rush/pnpm-lock.yaml, packages/framework-provider-azure/package.json
This PR removes the `@cdktf/provider-azurerm` from the `framework-provider-azure` package. This dependency was introduced in commit bc7438a40a8e5af85c47507585de5b7acef63e77, part of #1552, but this dependency is only required by the `framework-provider-azure-infrastructure` package. Including this dependency in `framework-provider-azure` was causing Booster apps to bloat.
* Removes `@cdktf/provider-azurerm` from `package.json` in `framework-provider-azure` package.
=> Remove unnecessary @cdktf/provider-azurerm dependency from Azure provider package

common/changes/@boostercloud/framework-core/fix_azure_deploy_2024-10-25-15-07.json, common/config/rush/pnpm-lock.yaml, packages/framework-provider-azure-infrastructure/src/infrastructure/synth/application-synth.ts
cdktf and the azurerm provider are now requiring that the Azure subscription ID is present on the `AzurermProvider`. Otherwise, it will give the following error during deployment:
```
Error: `subscription_id` is a required provider property when performing a plan/apply operation
```
* Added `subscriptionId` property when instancing `AzurermProvider` in the `ApplicationSynth` class.
=> Pass Azure subscription ID when instancing AzurermProvider object

common/changes/@boostercloud/framework-core/fix_optimistic_concurrency_2024-11-24-17-37.json, common/config/rush/pnpm-lock.yaml, packages/framework-provider-azure/src/helpers/query-helper.ts
The provider libraries have two methods for read model retrieval: `fetch` and `search`. In the implementation for the Azure provider, only the former was adding an `optimisticConcurrencyValue` property to the `boosterMetadata`. This value stores the Cosmos DB `_etag` property for the document and is used to handle optimistic concurrency scenarios.
Read model projection issues related to optimistic concurrency have been found due to the `search` method being used instead of `fetch`. Some read models weren't properly projected when a simultaneous update occurred because the optimistic concurrency verification wasn't happening due to the `optimisticConcurrencyValue` property not being in the `boosterMetadata`. 
This PR fixes this by including this …
=> Fix optimistic concurrency issue with read model projections

.github/workflows/re_test-integration-azure.yml, .github/workflows/re_test-integration-prepare.yml
=> Have Terraform installed in Azure integration test workflow

common/changes/@boostercloud/framework-core/fix_sensors_2025-03-24-19-38.json, common/config/rush/pnpm-lock.yaml, packages/framework-provider-azure/src/library/health-adapter.ts, packages/framework-provider-local/src/library/health-adapter.ts
Some health sensor endpoints require making an empty request to the GraphQL endpoint. Making this request with an empty body caused errors which caused other sensors to appear without response. (e.g., returned an empty array):
```text
error: [Booster]|BoosterGraphQLDispatcher#runGraphQLOperation: Received an empty GraphQL query
```
This PR fixes this error by sending a minimal GraphQL query in the request body.
* Modifies `health-adapter.ts`  in both Azure and local providers so that `isGraphQLFunctionUp` method sends the following in the request body:
```json
{
"query": "query { __typename }",
}
```
=> Fix sensor errors related to empty GraphQL query

common/changes/@boostercloud/framework-core/fix_event_handling_errors_2025-04-10-14-35.json, common/config/rush/pnpm-lock.yaml, packages/framework-core/src/booster-event-processor.ts, packages/framework-core/test/booster-event-processor.test.ts
It has been observed that unhandled errors during event handling (particularly in notification events) can halt the processing of other handlers within a batch, causing unwanted side effects such as projection failures. This PR addresses the issue by properly handling the `PromisesError` returned by event handler calls, preventing these errors from bubbling up and disrupting the event processing flow.
• Modifies the `dispatchEntityEventsToEventHandlers` method in the `BoosterEventProcessor` to properly handle event handler errors. It also replaces the for loop with `Promises.allSettledAndFulfilled`, ensuring the events are not processed sequentially.
• Adds unit tests for the updates described above.
=> Fix handling of event handler errors

.nvmrc, common/changes/@boostercloud/framework-core/codex-find-and-fix-a-bug-in-codebase_2025-05-20-12-19.json, common/config/rush/pnpm-lock.yaml, packages/framework-core/src/booster-event-stream-consumer.ts
- fix incorrect logger identifier in BoosterEventStreamConsumer
- `node common/scripts/install-run-rush.js test` *(fails: EHOSTUNREACH)*
- `npm test` in `packages/framework-core` *(fails: cross-env not found)*
=> Fix logger name in event stream consumer
